### ISSUE TITLE
翻译出错

### ISSUE THREAD

**Issue by weiby3** [dmMaze/BallonsTranslator#117]
中途跑着报错，看命令行输出，应该是超字数了？
```
[INFO   ] dl_manager:on_finish_setocr:713 - OCR set to mit48px_ctc
[INFO   ] dl_manager:on_finish_setinpainter:720 - Inpainter set to lama_mpe
[INFO   ] dl_manager:on_finish_setdetector:706 - Text detector set to ctd
[INFO   ] dl_manager:on_finish_settranslator:729 - Translator set to google
[ERROR  ] dl_manager:handleRunTimeException:808 - 翻译失败.: NotValidPayload()
Traceback (most recent call last):
  File "D:\ACGN\BallonTranslator\ui\dl_manager.py", line 228, in _run_translate_pipeline
  File "D:\ACGN\BallonTranslator\ui\dl_manager.py", line 192, in _translate_page
  File "D:\ACGN\BallonTranslator\dl\translators\__init__.py", line 174, in translate_textblk_lst
  File "D:\ACGN\BallonTranslator\dl\translators\__init__.py", line 141, in translate
  File "D:\ACGN\BallonTranslator\dl\translators\__init__.py", line 242, in _translate
  File "D:\ACGN\BallonTranslator\dl\translators\google_trans.py", line 181, in translate
  File "D:\ACGN\BallonTranslator\dl\translators\google_trans.py", line 55, in _validate_payload
dl.translators.exceptions.NotValidPayload: 88 --> text must be a valid text with maximum 5000 character, otherwise it cannot be translated

Traceback (most recent call last):
  File "D:\ACGN\BallonTranslator\ui\mainwindow.py", line 799, in on_pagtrans_finished
  File "D:\ACGN\BallonTranslator\ui\imgtrans_proj.py", line 166, in get_blklist_byidx
  File "D:\ACGN\BallonTranslator\ui\imgtrans_proj.py", line 47, in idx2pagename
KeyError: -1
```

**Comment by fkrsr** [comment]
同问，类似错误。而且似乎出了这个错误程序就卡死了？
希望至少可以跳过出错的页让程序继续。

**Comment by bropines** [comment]
> 同问，类似错误。而且似乎出了这个错误程序就卡死了？ 希望至少可以跳过出错的页让程序继续。

Can you record a video on how to repeat this bug?

**Comment by dmMaze** [comment]
你用的是老版本，请阅读readme用最新版

**Comment by fkrsr** [comment]
不好意思，我以为网盘里下的就是最新版本。
运行更新以后就没有问题了。

**Comment by Alexamenus** [comment]
I'm having this problem with the newest version.
