### ISSUE TITLE
mac m1报错了

### ISSUE THREAD

**Issue by novohool** [dmMaze/BallonsTranslator#118]
```
551 INFO: checking Analysis
551 INFO: Building Analysis because Analysis-00.toc is non existent
551 INFO: Initializing module dependency graph
553 INFO: Caching module graph hooks...
557 WARNING: Several hooks defined for module 'numpy'. Please take care they do not conflict.
558 INFO: Analyzing base_library.zip ...
1073 INFO: Loading module hook 'hook-heapq.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
1125 INFO: Loading module hook 'hook-encodings.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
1833 INFO: Loading module hook 'hook-pickle.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
2488 INFO: Caching module dependency graph...
2582 INFO: running Analysis Analysis-00.toc
2587 INFO: Analyzing /Users/admin/BallonsTranslator/ballontranslator/__main__.py
2696 INFO: Loading module hook 'hook-packaging.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
2712 INFO: Loading module hook 'hook-platform.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
2757 INFO: Loading module hook 'hook-xml.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
2866 INFO: Loading module hook 'hook-cv2.py' from '/opt/homebrew/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
2904 INFO: Loading module hook 'hook-numpy.py' from '/opt/homebrew/lib/python3.10/site-packages/numpy/_pyinstaller'...
3139 INFO: Loading module hook 'hook-numpy._pytesttester.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
3306 INFO: Loading module hook 'hook-difflib.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
3454 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
3879 INFO: Loading module hook 'hook-sysconfig.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
4152 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
4823 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-urllib3.packages.six.moves.py'.
5359 INFO: Loading module hook 'hook-charset_normalizer.py' from '/opt/homebrew/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
5476 INFO: Loading module hook 'hook-certifi.py' from '/opt/homebrew/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
5615 INFO: Loading module hook 'hook-matplotlib.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
8268 INFO: Processing pre-safe import module hook gi from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.py'.
8345 INFO: Loading module hook 'hook-PIL.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
8376 INFO: Loading module hook 'hook-PIL.Image.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
8689 INFO: Loading module hook 'hook-PIL.ImageFilter.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
9015 INFO: Loading module hook 'hook-jinja2.py' from '/opt/homebrew/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
9253 INFO: Loading module hook 'hook-pkg_resources.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
10057 INFO: Loading module hook 'hook-matplotlib.backends.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
10584 INFO: Processing pre-safe import module hook six.moves from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-six.moves.py'.
11314 INFO: Loading module hook 'hook-pytest.py' from '/opt/homebrew/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
11544 INFO: Loading module hook 'hook-importlib_metadata.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
11603 INFO: Loading module hook 'hook-py.py' from '/opt/homebrew/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
12274 INFO: Loading module hook 'hook-pygments.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
13213 INFO: Loading module hook 'hook-shapely.py' from '/opt/homebrew/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
13353 INFO: Loading module hook 'hook-torch.py' from '/opt/homebrew/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
14033 INFO: Loading module hook 'hook-sqlite3.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
17266 INFO: Loading module hook 'hook-scipy.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
17339 INFO: Loading module hook 'hook-scipy.io.matlab.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
17517 INFO: Loading module hook 'hook-scipy.sparse.csgraph.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
17631 INFO: Loading module hook 'hook-scipy.linalg.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
18430 INFO: Loading module hook 'hook-torchvision.ops.py' from '/opt/homebrew/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
20072 INFO: Processing pre-safe import module hook tensorflow from '/opt/homebrew/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-tensorflow.py'.
21591 INFO: Processing pre-find module path hook distutils from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
21801 INFO: Loading module hook 'hook-distutils.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
23382 INFO: Loading module hook 'hook-scipy.spatial.transform.rotation.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
25491 INFO: Loading module hook 'hook-regex.py' from '/opt/homebrew/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
26743 INFO: Loading module hook 'hook-wcwidth.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
33407 INFO: Loading module hook 'hook-setuptools.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
34139 INFO: Loading module hook 'hook-distutils.util.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
34626 INFO: Processing pre-safe import module hook win32com from '/opt/homebrew/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-win32com.py'.
35443 INFO: Loading module hook 'hook-lxml.py' from '/opt/homebrew/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
35765 INFO: Loading module hook 'hook-docx.py' from '/opt/homebrew/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
37707 INFO: Processing module hooks...
37827 INFO: Loading module hook 'hook-xml.dom.domreg.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
38085 INFO: Loading module hook 'hook-lxml.isoschematron.py' from '/opt/homebrew/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
38087 INFO: Loading module hook 'hook-lxml.etree.py' from '/opt/homebrew/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
38500 INFO: Loading module hook 'hook-PyQt6.QtWidgets.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
42689 INFO: Loading module hook 'hook-scipy.special._ufuncs.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
42689 INFO: Loading module hook 'hook-PyQt6.QtGui.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
42759 INFO: Loading module hook 'hook-PyQt6.QtCore.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
42814 INFO: Loading module hook 'hook-setuptools.msvc.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
43591 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
43650 INFO: Loading module hook 'hook-scipy.special._ellip_harm_2.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
43650 INFO: Loading module hook 'hook-matplotlib.backends.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
43650 INFO: Matplotlib backend selection method: automatic discovery of used backends
43803 INFO: Trying determine the default backend as first importable candidate from the list: ['MacOSX', 'Qt5Agg', 'Gtk3Agg', 'TkAgg', 'WxAgg']
47592 INFO: Selected matplotlib backends: ['MacOSX']
47598 INFO: Loading module hook 'hook-scipy.stats._stats.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
47599 INFO: Loading module hook 'hook-PyQt6.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
47605 INFO: Loading module hook 'hook-PyQt6.QtOpenGLWidgets.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
48464 INFO: Loading module hook 'hook-PyQt6.QtOpenGL.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
48499 INFO: Loading module hook 'hook-lxml.objectify.py' from '/opt/homebrew/lib/python3.10/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
48500 INFO: Loading module hook 'hook-PyQt6.QtDBus.py' from '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks'...
48592 INFO: Looking for ctypes DLLs
48603 WARNING: Library user32 required via ctypes not found
48605 WARNING: Library vcruntime140_1.dll required via ctypes not found
48606 WARNING: Library msvcp140.dll required via ctypes not found
48607 WARNING: Library vcruntime140.dll required via ctypes not found
48628 WARNING: Ignoring data/libs/patchmatch_inpaint.dll imported from /Users/admin/BallonsTranslator/ballontranslator/dl/inpaint/patch_match.py - only basenames are supported with ctypes imports!
48634 WARNING: Library dwmapi required via ctypes not found
48634 WARNING: Library user32 required via ctypes not found
48636 WARNING: Library dwmapi required via ctypes not found
48637 WARNING: Library user32 required via ctypes not found
48649 INFO: Analyzing run-time hooks ...
48661 INFO: Including run-time hook '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
48662 INFO: Including run-time hook '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py'
48663 INFO: Including run-time hook '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
48664 INFO: Including run-time hook '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgres.py'
48666 INFO: Including run-time hook '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pyqt6.py'
48666 INFO: Including run-time hook '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_mplconfig.py'
48667 INFO: Including run-time hook '/opt/homebrew/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_setuptools.py'
48757 INFO: Looking for dynamic libraries
/opt/homebrew/lib/python3.10/site-packages/PyInstaller/building/build_main.py:175: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
/opt/homebrew/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: dlopen(/opt/homebrew/lib/python3.10/site-packages/torchvision/image.so, 0x0006): Symbol not found: (__ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEENS6_INS2_12MemoryFormatEEE)
  Referenced from: '/opt/homebrew/lib/python3.10/site-packages/torchvision/image.so'
  Expected in: '/opt/homebrew/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib'
  warn(f"Failed to load image Python extension: {e}")
100947 INFO: Created a temporary directory at /tmp/tmpa5_i0uoj
100947 INFO: Writing /tmp/tmpa5_i0uoj/_remote_module_non_scriptable.py
109200 WARNING: Cannot find path ./libtorch_python.dylib (needed by /opt/homebrew/lib/python3.10/site-packages/torchvision/_C.so)
109200 WARNING: Cannot find path ./libtorch.dylib (needed by /opt/homebrew/lib/python3.10/site-packages/torchvision/_C.so)
109200 WARNING: Cannot find path ./libc10.dylib (needed by /opt/homebrew/lib/python3.10/site-packages/torchvision/_C.so)
109200 WARNING: Cannot find path ./libtorch_cpu.dylib (needed by /opt/homebrew/lib/python3.10/site-packages/torchvision/_C.so)
158568 INFO: Looking for eggs
158568 INFO: Using Python library /opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/Python
158591 INFO: Warnings written to /Users/admin/BallonsTranslator/ballontranslator/build/__main__/warn-__main__.txt
158747 INFO: Graph cross-reference written to /Users/admin/BallonsTranslator/ballontranslator/build/__main__/xref-__main__.html
159166 INFO: Appending 'datas' from .spec
159177 INFO: checking PYZ
159177 INFO: Building PYZ because PYZ-00.toc is non existent
159177 INFO: Building PYZ (ZlibArchive) /Users/admin/BallonsTranslator/ballontranslator/build/__main__/PYZ-00.pyz
163007 INFO: Building PYZ (ZlibArchive) /Users/admin/BallonsTranslator/ballontranslator/build/__main__/PYZ-00.pyz completed successfully.
163044 INFO: EXE target arch: arm64
163044 INFO: Code signing identity: None
163044 INFO: checking PKG
163044 INFO: Building PKG because PKG-00.toc is non existent
163044 INFO: Building PKG (CArchive) __main__.pkg
163054 INFO: Building PKG (CArchive) __main__.pkg completed successfully.
163055 INFO: Bootloader /opt/homebrew/lib/python3.10/site-packages/PyInstaller/bootloader/Darwin-64bit/runw
163055 INFO: checking EXE
163055 INFO: Building EXE because EXE-00.toc is non existent
163055 INFO: Building EXE from EXE-00.toc
163055 INFO: Copying bootloader EXE to /Users/admin/BallonsTranslator/ballontranslator/build/__main__/__main__
163055 INFO: Converting EXE to target arch (arm64)
163075 INFO: Removing signature(s) from EXE
163086 INFO: Appending PKG archive to EXE
163093 INFO: Fixing EXE headers for code signing
163097 INFO: Re-signing the EXE
163131 INFO: Building EXE from EXE-00.toc completed successfully.
163139 INFO: checking COLLECT
163139 INFO: Building COLLECT because COLLECT-00.toc is non existent
163139 INFO: Building COLLECT COLLECT-00.toc
Traceback (most recent call last):
  File "/opt/homebrew/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
  File "/opt/homebrew/lib/python3.10/site-packages/PyInstaller/__main__.py", line 194, in _console_script_run
    run()
  File "/opt/homebrew/lib/python3.10/site-packages/PyInstaller/__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/opt/homebrew/lib/python3.10/site-packages/PyInstaller/__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 977, in main
    build(specfile, distpath, workpath, clean_build)
  File "/opt/homebrew/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 899, in build
    exec(code, spec_namespace)
  File "__main__.spec", line 60, in <module>
    coll = COLLECT(
  File "/opt/homebrew/lib/python3.10/site-packages/PyInstaller/building/api.py", line 934, in __init__
    self.__postinit__()
  File "/opt/homebrew/lib/python3.10/site-packages/PyInstaller/building/datastruct.py", line 173, in __postinit__
    self.assemble()
  File "/opt/homebrew/lib/python3.10/site-packages/PyInstaller/building/api.py", line 977, in assemble
    src_name = checkCache(
  File "/opt/homebrew/lib/python3.10/site-packages/PyInstaller/building/utils.py", line 368, in checkCache
    osxutils.binary_to_target_arch(cachedfile, target_arch, display_name=fnm)
  File "/opt/homebrew/lib/python3.10/site-packages/PyInstaller/utils/osx.py", line 323, in binary_to_target_arch
    raise IncompatibleBinaryArchError(
PyInstaller.utils.osx.IncompatibleBinaryArchError: /opt/homebrew/lib/python3.10/site-packages/torch/_dl.cpython-310-darwin.so is incompatible with target arch arm64 (has arch: x86_64)!
```

**Comment by dmMaze** [comment]
现在在mac m1上比较能用了，还有问题再另开
