### ISSUE TITLE
Error while testing

### ISSUE THREAD

**Issue by hsk20011** [dmMaze/BallonsTranslator#143]
[INFO   ] dl_manager:on_finish_setdetector:719 - Text detector set to ctd
[INFO   ] dl_manager:on_finish_setocr:726 - OCR set to mit48px_ctc
[INFO   ] dl_manager:on_finish_setinpainter:733 - Inpainter set to lama_mpe
[WARNING] dl_manager:setTranslator:687 - Terminating a running translation thread.
[INFO   ] dl_manager:on_finish_settranslator:742 - Translator set to caiyun
[INFO   ] dl_manager:on_finish_settranslator:742 - Translator set to baidu
[INFO   ] dl_manager:on_finish_settranslator:742 - Translator set to papago
Traceback (most recent call last):
  File "C:\WPy64-39100\YHB\BallonsTranslator\ballontranslator\ui\dl_manager.py", line 411, in run
    self.job()
  File "C:\WPy64-39100\YHB\BallonsTranslator\ballontranslator\ui\dl_manager.py", line 362, in _imgtrans_pipeline
    self.ocr.run_ocr(img, blk_list)
  File "C:\WPy64-39100\YHB\BallonsTranslator\ballontranslator\dl\ocr\__init__.py", line 39, in run_ocr
    self.ocr_blk_list(img, blk_list)
  File "C:\WPy64-39100\YHB\BallonsTranslator\ballontranslator\dl\ocr\__init__.py", line 237, in ocr_blk_list
    return self.model(img, blk_list)
  File "C:\WPy64-39100\YHB\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\WPy64-39100\YHB\BallonsTranslator\ballontranslator\dl\ocr\mit48px_ctc.py", line 445, in __call__
    texts = self.net.decode(images, widths, 0)
  File "C:\WPy64-39100\YHB\BallonsTranslator\ballontranslator\dl\ocr\mit48px_ctc.py", line 299, in decode
    feats = self.encoders(feats.permute(0, 2, 1))
  File "C:\WPy64-39100\YHB\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\WPy64-39100\YHB\env\lib\site-packages\torch\nn\modules\transformer.py", line 306, in forward
    output = mod(output, src_mask=mask, is_causal=is_causal, src_key_padding_mask=src_key_padding_mask_for_layers)
  File "C:\WPy64-39100\YHB\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() got an unexpected keyword argument 'is_causal'

**Comment by bropines** [comment]
This is a torch 2.0 problem. I will try to solve it one of these days as soon as I am free. Or someone can send their PR.
