### ISSUE TITLE
请问翻译失败是什么原因

### ISSUE THREAD

**Issue by shenbiren87** [dmMaze/BallonsTranslator#152]

**Comment by shenbiren87** [comment]
dl.translators.exceptions.RequestError: Request exception can happen due to an api connection error. Please check your connection and try again
 why？

**Comment by bropines** [comment]
> dl.translators.exceptions.RequestError: Request exception can happen due to an api connection error. Please check your connection and try again why？

I can get a screenshot of the error from you as well as a full error record (copy the text and paste)
There seems to be a problem with connecting to the translator server. If it's not difficult, check which server for translation (you have google)
For people living in China, there is a separate regional domain
![image](https://github.com/dmMaze/BallonsTranslator/assets/57861007/9305cc4e-676c-4ec5-8cf7-b7bfe136e1af)

**Comment by shenbiren87** [comment]
Traceback (most recent call last):
  File "D:\tp\manga\BALLON~1.0-C\BALLON~1\ui\dl_manager.py", line 223, in _run_translate_pipeline
  File "D:\tp\manga\BALLON~1.0-C\BALLON~1\ui\dl_manager.py", line 187, in _translate_page
  File "D:\tp\manga\BALLON~1.0-C\BALLON~1\dl\translators\__init__.py", line 149, in translate_textblk_lst
  File "D:\tp\manga\BALLON~1.0-C\BALLON~1\dl\translators\__init__.py", line 122, in translate
  File "D:\tp\manga\BALLON~1.0-C\BALLON~1\dl\translators\__init__.py", line 207, in _translate
  File "D:\tp\manga\BALLON~1.0-C\BALLON~1\dl\translators\google_trans.py", line 193, in translate
dl.translators.exceptions.RequestError: Request exception can happen due to an api connection error. Please check your connection and try again

**Comment by bropines** [comment]
> Traceback (most recent call last): File "D:\tp\manga\BALLON~1.0-C\BALLON~1\ui\dl_manager.py", line 223, in _run_translate_pipeline File "D:\tp\manga\BALLON~1.0-C\BALLON~1\ui\dl_manager.py", line 187, in _translate_page File "D:\tp\manga\BALLON~1.0-C\BALLON~1\dl\translators__init__.py", line 149, in translate_textblk_lst File "D:\tp\manga\BALLON~1.0-C\BALLON~1\dl\translators__init__.py", line 122, in translate File "D:\tp\manga\BALLON~1.0-C\BALLON~1\dl\translators__init__.py", line 207, in _translate File "D:\tp\manga\BALLON~1.0-C\BALLON~1\dl\translators\google_trans.py", line 193, in translate dl.translators.exceptions.RequestError: Request exception can happen due to an api connection error. Please check your connection and try again

Have you tried changing the translation server?

**Comment by shenbiren87** [comment]
yes still not working

**Comment by bropines** [comment]
@dmMaze hmmm, maybe google translate stopped working

**Comment by bropines** [comment]
> yes still not working

Try using other translation services.
