### ISSUE TITLE
用chatgpt翻译显示翻译失败

### ISSUE THREAD

**Issue by wtgjxy0668** [dmMaze/BallonsTranslator#173]
[WARNING] connectionpool:urlopen:751 - Retrying (%r) after connection broken by '%r': %s
[WARNING] connectionpool:urlopen:751 - Retrying (%r) after connection broken by '%r': %s
[INFO   ] trans_chatgpt:_translate:227 - Used 104 tokens (Total: 245)
[ERROR  ] module_manager:handleRunTimeException:826 - 翻译失败.: AssertionError()
Traceback (most recent call last):
  File "W:\BallonTranslator\BallonsTranslator-chatgpt\ui\module_manager.py", line 232, in _run_translate_pipeline
    self._translate_page(self.imgtrans_proj.pages, page_key, raise_exception=True, emit_finished=False)
  File "W:\BallonTranslator\BallonsTranslator-chatgpt\ui\module_manager.py", line 202, in _translate_page
    raise e
  File "W:\BallonTranslator\BallonsTranslator-chatgpt\ui\module_manager.py", line 194, in _translate_page
    self.translator.translate_textblk_lst(page)
  File "W:\BallonTranslator\BallonsTranslator-chatgpt\modules\translators\base.py", line 182, in translate_textblk_lst
    translations = self.translate(text_list)
  File "W:\BallonTranslator\BallonsTranslator-chatgpt\modules\translators\base.py", line 160, in translate
    assert len(text_trans) == len(text)
AssertionError

![image](https://github.com/dmMaze/BallonsTranslator/assets/100186680/87dfc5cf-fde8-4389-aa07-cb3d55283116)

没有python基础；；不懂

**Comment by dmMaze** [comment]
你跑的这个commit hash是 3006d2a43a170cbdde24913d2b3d3ec618018aa3 吗

**Comment by wtgjxy0668** [comment]
> 你看到的这个提交哈希值是[3006d2a](https://github.com/dmMaze/BallonsTranslator/commit/3006d2a43a170cbdde24913d2b3d3ec618018aa3)吗？

不是；；我用的是 https://github.com/dmMaze/BallonsTranslator/commit/40b0fa11b5af3cd935cc007e6299ad1f19cc3aef

**Comment by wtgjxy0668** [comment]
> 你看到的这个提交哈希值是[3006d2a](https://github.com/dmMaze/BallonsTranslator/commit/3006d2a43a170cbdde24913d2b3d3ec618018aa3)吗？

但是我用 https://github.com/dmMaze/BallonsTranslator/commit/3006d2a43a170cbdde24913d2b3d3ec618018aa3 翻译到一半又翻译失败了。
![image](https://github.com/dmMaze/BallonsTranslator/assets/100186680/f4bdc2b1-fda8-43a3-9ef9-f3f199367184)

**Comment by wtgjxy0668** [comment]
> 你看到的这个提交哈希值是[3006d2a](https://github.com/dmMaze/BallonsTranslator/commit/3006d2a43a170cbdde24913d2b3d3ec618018aa3)吗？

但是我用 https://github.com/dmMaze/BallonsTranslator/commit/40b0fa11b5af3cd935cc007e6299ad1f19cc3aef 来翻译，结果翻译到一半又翻译失败了
![image](https://github.com/dmMaze/BallonsTranslator/assets/100186680/854158ae-48ea-4b21-b830-e8852aa48ac5)
![image](https://github.com/dmMaze/BallonsTranslator/assets/100186680/d5d62e6e-f2c1-478c-82c6-0b389b64f0be)

**Comment by wtgjxy0668** [comment]
> 你跑的这个commit hash是 [3006d2a](https://github.com/dmMaze/BallonsTranslator/commit/3006d2a43a170cbdde24913d2b3d3ec618018aa3) 吗

但是我用 https://github.com/dmMaze/BallonsTranslator/commit/3006d2a43a170cbdde24913d2b3d3ec618018aa3 来翻译，结果翻译到一半又翻译失败了
![Clip_20230709_174249](https://github.com/dmMaze/BallonsTranslator/assets/100186680/14f9e497-1774-4e32-be17-18a65c124ab3)
![Clip_20230709_174300](https://github.com/dmMaze/BallonsTranslator/assets/100186680/78826ad3-880b-4978-bb52-7fedd3271224)

**Comment by wtgjxy0668** [comment]
![image](https://github.com/dmMaze/BallonsTranslator/assets/100186680/07b63056-d9bd-4e71-8a6f-092ac3337989)
run了一下还闪退了；；

**Comment by dmMaze** [comment]
可以试试 64ffeed1eb1e33ed2d4ae76b0aa5d8e1c263dd97 (也就是最新的dev branch)
翻译失败的原因：
现在把一整页的多段文字通过某种分隔符拼接起来一起给GPT翻译，然后把翻译结果根据分隔符拆分回原来的多段文字，GPT翻译结果有时候会弄乱分隔符导致拆分后的翻译段落数量和原文对不上就抛异常了

现在程序里改成了对不上就重试，如果重试次数超过retry attempts就返回同样数量的空白段，控制台也会打印错误而不会让程序挂掉

**Comment by wtgjxy0668** [comment]
> 可以试试 [64ffeed](https://github.com/dmMaze/BallonsTranslator/commit/64ffeed1eb1e33ed2d4ae76b0aa5d8e1c263dd97) (也就是最新的dev branch) 翻译失败的原因： 现在把一整页的多段文字通过某种分隔符拼接起来一起给GPT翻译，然后把翻译结果根据分隔符拆分回原来的多段文字，GPT翻译结果有时候会弄乱分隔符导致拆分后的翻译段落数量和原文对不上就抛异常了
> 
> 现在程序里改成了对不上就重试，如果重试次数超过retry attempts就返回同样数量的空白段，控制台也会打印错误而不会让程序挂掉

好的，用了。我第一次翻译，二十多页的漫画翻译到还剩几页失败了，重新打开程序第二次翻译没反应但在cmd里已经红色失败。第三次翻译才成功。这是第一次失败的图 ![image](https://github.com/dmMaze/BallonsTranslator/assets/100186680/430678a0-5457-4175-8db5-cefdc3355db2)

**Comment by dmMaze** [comment]
> > 可以试试 [64ffeed](https://github.com/dmMaze/BallonsTranslator/commit/64ffeed1eb1e33ed2d4ae76b0aa5d8e1c263dd97) (也就是最新的dev branch) 翻译失败的原因： 现在把一整页的多段文字通过某种分隔符拼接起来一起给GPT翻译，然后把翻译结果根据分隔符拆分回原来的多段文字，GPT翻译结果有时候会弄乱分隔符导致拆分后的翻译段落数量和原文对不上就抛异常了
> > 现在程序里改成了对不上就重试，如果重试次数超过retry attempts就返回同样数量的空白段，控制台也会打印错误而不会让程序挂掉
> 
> 好的，用了。我第一次翻译，二十多页的漫画翻译到还剩几页失败了，重新打开程序第二次翻译没反应但在cmd里已经红色失败。第三次翻译才成功。这是第一次失败的图 ![image](https://user-images.githubusercontent.com/100186680/252142641-430678a0-5457-4175-8db5-cefdc3355db2.png)

应该是高峰段openai堵了...用gpt就是容易失败所以这些异常现在都默认返回空字符串了 https://github.com/dmMaze/BallonsTranslator/commit/c3f81c3d82296698ae418442a07e66f9b31494ed

**Comment by wtgjxy0668** [comment]
> 

是的，现在gpt的问题还是太多了。翻译还得用gpt3，用3.5的还是会失败，gpt4直接用不了。

**Comment by wtgjxy0668** [comment]
> > > 可以试试 [64ffeed](https://github.com/dmMaze/BallonsTranslator/commit/64ffeed1eb1e33ed2d4ae76b0aa5d8e1c263dd97) (也就是最新的dev branch) 翻译失败的原因： 现在把一整页的多段文字通过某种分隔符拼接起来一起给GPT翻译，然后把翻译结果根据分隔符拆分回原来的多段文字，GPT翻译结果有时候会弄乱分隔符导致拆分后的翻译段落数量和原文对不上就抛异常了
> > > 现在程序里改成了对不上就重试，如果重试次数超过retry attempts就返回同样数量的空白段，控制台也会打印错误而不会让程序挂掉
> > 
> > 
> > 好的，用了。我第一次翻译，二十多页的漫画翻译到还剩几页失败了，重新打开程序第二次翻译没反应但在cmd里已经红色失败。第三次翻译才成功。这是第一次失败的图 ![image](https://user-images.githubusercontent.com/100186680/252142641-430678a0-5457-4175-8db5-cefdc3355db2.png)
> 
> 应该是高峰段openai堵了...用gpt就是容易失败所以这些异常现在都默认返回空字符串了 [c3f81c3](https://github.com/dmMaze/BallonsTranslator/commit/c3f81c3d82296698ae418442a07e66f9b31494ed)

是的，现在gpt的问题还是太多了。翻译还得用gpt3，用3.5的还是会失败，gpt4直接用不了。换上的空字符没提醒翻译失败，翻译完才会知道没翻译

**Comment by ikazoa** [comment]
gpt缩行是老毛病了，一直没有很好的解决方案，本质还是因为提交的文本不够规范。本来能连成完整的一句话却非要分割后提交，而gpt又过于“智能”擅自把两句合并为一句。最终造成了返回的和提交的数目不一致。

**Comment by hq5566** [comment]
我已成功，可以说效果很好。请见我发的贴。

**Comment by wtgjxy0668** [comment]
> 我已成功，可以说效果很好。请见我发的贴。

我也能用，就是有很多翻译不上

**Comment by wtgjxy0668** [comment]
@dmMaze  大佬我这个是显存不够了吗还是怎么回事，本来翻的好好的，为什么翻这个文件夹的图片会闪退

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 900.00 MiB (GPU 0; 6.00 GiB total capacity; 4.13 GiB already allocated; 0 bytes free; 4.58 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by hq5566** [comment]
> > 我已成功，可以说效果很好。请见我发的贴。
> 
> 我也能用，就是有很多翻译不上

你所描述的问题我看了，有可能是在安装中除了什么问题，有可能是环境没有设置好。建议按照作者的说明，重新安装。我不清楚具体情况，有可能需要打开python程序来看看，逐步运行到出现报错那行，再看是否需要修改什么参数。你可能要请问程序编写者，请作者帮忙。我的显存就是6G。没绑卡之前基本OpenAi API 是无法顺利翻译的，哪怕是GPT3。在Openai API account绑定支付方式后，速度唰地一下起来了，翻译质量比谷歌和微软还好。按需按使用量来收费我觉得是合理的，不贵。我是N卡，以前试whsiper时安了Cuda，现在的翻译速度不慢。只是我那天在外面，没有插电试。

**Comment by ikazoa** [comment]
那是因为绑卡之前的免费账户每分钟只能调用三次api，绑卡后可以提高数十倍。网上卖低价账号的有很多，不到100就能买到120刀额度的账号，不过因为是黑卡只能用一个月。

**Comment by hq5566** [comment]
最好是不要买黑卡，或许有其它途径可以完成绑定 请千万注意交易安全。


On Jul 18, 2023, at 10:45 AM, ikazoa ***@***.***> wrote:

﻿

那是因为绑卡之前的免费账户每分钟只能调用三次api，绑卡后可以提高数十倍。网上卖低价账号的有很多，不到100就能买到120刀额度的账号，不过因为是黑卡只能用一个月。

**Comment by xuejianxianzun** [comment]
> 可以试试 [64ffeed](https://github.com/dmMaze/BallonsTranslator/commit/64ffeed1eb1e33ed2d4ae76b0aa5d8e1c263dd97) (也就是最新的dev branch) 翻译失败的原因： 现在把一整页的多段文字通过某种分隔符拼接起来一起给GPT翻译，然后把翻译结果根据分隔符拆分回原来的多段文字，GPT翻译结果有时候会弄乱分隔符导致拆分后的翻译段落数量和原文对不上就抛异常了
> 
> 现在程序里改成了对不上就重试，如果重试次数超过retry attempts就返回同样数量的空白段，控制台也会打印错误而不会让程序挂掉

也就是说一整页的文本是一次发送的吗，感觉很好，可以完善语境
