### ISSUE TITLE
dev版无法更换字体颜色

### ISSUE THREAD

**Issue by didala083** [dmMaze/BallonsTranslator#249]
文字框更换字体颜色后无效，后台提示如下：

Traceback (most recent call last):
  File "BallonsTranslator\ui\fontformatpanel.py", line 411, in onColorChanged
    self.on_param_changed('frgb', frgb)
  File "BallonsTranslator\ui\fontformatpanel.py", line 398, in on_param_changed
    func = FM.handle_ffmt_change.get(param_name)
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by didala083** [comment]
2023年10月11日拉取最新更新就有这个问题了

**Comment by dmMaze** [comment]
感谢提醒，https://github.com/dmMaze/BallonsTranslator/commit/0c4e98bdf6f6eed8c7ac4c3c43d8e026904b9e9e 已修
