### ISSUE TITLE
从源码运行会出现cuda内存不足，直接使用发行版则不会

### ISSUE THREAD

**Issue by wjz2001** [dmMaze/BallonsTranslator#262]
如题，日志如下：
`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 730.00 MiB (GPU 0; 4.00 GiB total capacity; 2.91 GiB already allocated; 0 bytes free; 3.01 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`
两个版本设置完全相同，发行版不论使用何种ocr和修补工具都可以正常运行，而源码则不会。

**Comment by dmMaze** [comment]
设置真的一样吗，哪步挂的，给下完整的traceback

**Comment by wjz2001** [comment]
> 设置真的一样吗，哪步挂的，给下完整的traceback

![QQ截图20231029222215.png](https://s1.locimg.com/2023/10/29/c6600ac6442bc.png)

Traceback (most recent call last):
  File "D:\BallonsTranslator\modules\inpaint\base.py", line 53, in inpaint
    return self._inpaint(img, mask)
  File "D:\BallonsTranslator\ballontrans_pylibs_win\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\BallonsTranslator\modules\inpaint\base.py", line 302, in _inpaint
    img_inpainted_torch = self.model(img_torch, mask_torch, rel_pos, direct)
  File "D:\BallonsTranslator\modules\inpaint\lama.py", line 321, in __call__
    predicted_img = self.generator(img, mask, rel_pos, direct)
  File "D:\BallonsTranslator\ballontrans_pylibs_win\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\BallonsTranslator\modules\inpaint\lama.py", line 128, in forward
    x_l, x_g = self.model[:2](masked_img)
  File "D:\BallonsTranslator\ballontrans_pylibs_win\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\BallonsTranslator\ballontrans_pylibs_win\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "D:\BallonsTranslator\ballontrans_pylibs_win\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\BallonsTranslator\modules\inpaint\ffc.py", line 256, in forward
    x_l, x_g = self.ffc(x)
  File "D:\BallonsTranslator\ballontrans_pylibs_win\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\BallonsTranslator\modules\inpaint\ffc.py", line 225, in forward
    out_xl = self.convl2l(x_l) + self.convg2l(x_g) * g2l_gate
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 730.00 MiB (GPU 0; 4.00 GiB total capacity; 2.75 GiB already allocated; 0 bytes free; 2.83 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\BallonsTranslator\ui\module_manager.py", line 464, in run
    self.job()
  File "D:\BallonsTranslator\ui\module_manager.py", line 429, in _imgtrans_pipeline
    inpainted = self.inpainter.inpaint(img, mask, blk_list)
  File "D:\BallonsTranslator\modules\inpaint\base.py", line 57, in inpaint
    return self._inpaint(img, mask)
  File "D:\BallonsTranslator\ballontrans_pylibs_win\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\BallonsTranslator\modules\inpaint\base.py", line 302, in _inpaint
    img_inpainted_torch = self.model(img_torch, mask_torch, rel_pos, direct)
  File "D:\BallonsTranslator\modules\inpaint\lama.py", line 318, in __call__
    rel_pos, direct = self.mpe(rel_pos, direct)
  File "D:\BallonsTranslator\ballontrans_pylibs_win\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\BallonsTranslator\modules\inpaint\lama.py", line 247, in forward
    rel_pos_emb = self.rel_pos_emb(rel_pos).reshape(b, h, w, -1).permute(0, 3, 1, 2) * self.alpha5
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 730.00 MiB (GPU 0; 4.00 GiB total capacity; 2.91 GiB already allocated; 0 bytes free; 2.92 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by dmMaze** [comment]
9abc7bb 算是修了
4G显存lamampe全尺寸修复显存就是不够，之前做了一些剪裁后再修复和判断是否需要修复的优化, 修复尺寸大致是漫画里最大的需要修复的文本块的大小, 发布版之后对gpu挪掉了这个优化, 现在加回来了
所以现在4G跑这个爆显存其实还是概率问题，你可以暂时先只跑其它三个阶段最后再过一遍修复，以后我会让它显存不足fallback到cpu什么的

**Comment by didala083** [comment]
对于这个问题我也想提个建议，能不能在右键菜单里把一键抹字给单独列出来，直接用OCR+翻译+抹字嵌字的话很不方便。实际使用中需要切换OCR引擎，很难有一个引擎全部识别出来的。

**Comment by dmMaze** [comment]
> 对于这个问题我也想提个建议，能不能在右键菜单里把一键抹字给单独列出来，直接用OCR+翻译+抹字嵌字的话很不方便。实际使用中需要切换OCR引擎，很难有一个引擎全部识别出来的。

dev版可以各个阶段单独跑啊
<img width="488" alt="image" src="https://github.com/dmMaze/BallonsTranslator/assets/51270320/e9f4072f-7079-45f4-ba92-4f1c0e8a698e">

**Comment by didala083** [comment]
已经用上了dev版，菜单里那个貌似是所有页面一起跑，有时候需要页面内选定几个框跑，这个菜单里的好像实现不了

**Comment by dmMaze** [comment]
用新加的[lama_large_512px](https://github.com/dmMaze/BallonsTranslator/commit/3fa1ef97543d934ae1142435c4422eef6c273510)吧, precision选bf16和fp16都能减少显存占用
