### ISSUE TITLE
正则报错？ 

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#264]
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/1d926e0d-e9ea-404f-b0a3-37969e666525)

![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/a5d90b56-ffd2-40eb-80be-b213016cd1f9)
通篇的 大红字报错 问了下GPT说是正则问题？ 
大佬您看  看
[ERROR  ] keywordsubwidget:sub_text:127 - Invalid regex expression at line 1842:
[ERROR  ] keywordsubwidget:sub_text:128 - Traceback (most recent call last):
  File "D:\BL\BallonsTranslator\ui\keywordsubwidget.py", line 125, in sub_text
    text = re.sub(regexr, subpair['sub'], text)
  File "re.py", line 209, in sub
  File "re.py", line 303, in _compile
  File "sre_compile.py", line 788, in compile
  File "sre_parse.py", line 969, in parse
re.error: unbalanced parenthesis at position 2

**Comment by dmMaze** [comment]
就是你加的某个正则表达式不合法，程序里直接跳过这个不合法的正则并报错了，不是软件bug

**Comment by lhj5426** [comment]
> 就是你加的某个正则表达式不合法，程序里直接跳过这个不合法的正则并报错了，不是软件bug

行吧 原来如此感谢  麻烦大佬了 我去排查下
