### ISSUE TITLE
When selecting 3 or more text blocks and deleting: IndexError

### ISSUE THREAD

**Issue by tak2hu** [dmMaze/BallonsTranslator#273]
Traceback (most recent call last):
  File "D:\BallonsTranslator\ui\scenetext_manager.py", line 640, in on_incanvas_selection_changed
    self.textEditList.set_selected_list([t.idx for t in textitems])
  File "D:\BallonsTranslator\ui\textedit_area.py", line 593, in set_selected_list
    pw = self.pairwidget_list[idx]
         ~~~~~~~~~~~~~~~~~~~~^^^^^
IndexError: list index out of range
Press any key to continue . . .

**Comment by dmMaze** [comment]
can't reproduce it, can you share the imgtrans_*.json and images? send to [beneathlimbo@gmail.com](mailto:beneathlimbo@gmail.com) if its more convenient

**Comment by tak2hu** [comment]
Sorry I forgot to write “deleting”, my bad
