### ISSUE TITLE
Cannot execute

### ISSUE THREAD

**Issue by gyeolls** [dmMaze/BallonsTranslator#277]
py version:  3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
py executable:  C:\Users\USER\AppData\Local\Programs\Python\Python311\python.exe
version: 1.4.0
branch: dev
Commit hash: 26f6d2e0a2bff462d01a6710f0a221d67c8706fe
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\HentaiTranslator\launch.py", line 234, in <module>
    main()
  File "C:\Users\USER\Desktop\HentaiTranslator\launch.py", line 164, in main
    load_modules()
  File "C:\Users\USER\Desktop\HentaiTranslator\launch.py", line 101, in load_modules
    load_translators()
  File "C:\Users\USER\Desktop\HentaiTranslator\launch.py", line 97, in load_translators
    importlib.import_module('modules.translators.' + translator.replace('.py', ''))
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\USER\Desktop\HentaiTranslator\modules\translators\trans_chatgpt.py", line 5, in <module>
    import openai.error
ModuleNotFoundError: No module named 'openai.error'
[INFO   ] utils:dump_compile_times:247 - TorchDynamo compilation metrics:
Function, Runtimes (s)
[INFO   ] utils:dump_compile_times:247 - TorchDynamo compilation metrics:
Function, Runtimes (s)
[2023-11-08 20:51:11,944] torch._dynamo.utils: [INFO] TorchDynamo compilation metrics:
[2023-11-08 20:51:11,944] torch._dynamo.utils: [INFO] Function, Runtimes (s)

How can I do

**Comment by gyeolls** [comment]
The openai is installed, and I have also proceeded with the reinstallation

**Comment by gyeolls** [comment]
general system python
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32

**Comment by bropines** [comment]
> general system python Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32

Apparently, you have a rather specific torch that we do not support. if you don't want to break your head, use the auto-installer from the readme, if you call yourself, create a separate venv for the ballon with your packages, it's easier, better and there will be no suffering.

**Comment by gyeolls** [comment]
I've already reinstalled Python again and again, and followed the readme

**Comment by bropines** [comment]
> I've already reinstalled Python again and again, and followed the readme

I'll check it on Python 3.11

**Comment by bropines** [comment]
> I've already reinstalled Python again and again, and followed the readme

The openAI chatGPT library does not run on 3.11. @dmMaze can you fix it?

**Comment by bropines** [comment]
> I've already reinstalled Python again and again, and followed the readme

As a temporary solution, comment out the line `openai.error`
```python
import re
import openai
#import openai.error
import time
from typing import List, Dict, Union
import yaml
from .base import BaseTranslator, register_translator
```

**Comment by dmMaze** [comment]
@bropines it seems the newest openai python library made a lot of API changes and broke the error handling, do you have a key and can you confirm the translation still works on the newest openai?

**Comment by bropines** [comment]
> @bropines it seems the newest openai python library made a lot of API changes and broke the error handling, do you have a key and can you confirm the translation still works on the newest openai?

Well, it translates without question. 
![image](https://github.com/dmMaze/BallonsTranslator/assets/57861007/d81f6f5e-2c50-4ce1-a1c7-64727b09b3de)

**Comment by gyeolls** [comment]
So, what is the appropriate Python version

**Comment by bropines** [comment]
> So, what is the appropriate Python version

Well, I checked, 3.10 is the current and priority for us, 3.11 is checked, it works, but we didn't check all the functions.  If you want to simplify working with python on windows, it's better to put [pyenv-win](https://github.com/pyenv-win/pyenv-win ) . It will simplify the installation of several python versions, it is also better for ballon to create a separate venv so as not to trash the pip system storage.

**Comment by bropines** [comment]
have you updated the repository? git pull
