### ISSUE TITLE
新版报错 

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#281]
刚开始更新完运行是好好的
我什么都没做 就是重启了下电脑
因为做了一天的漫画 发布到E站之后电脑有点卡
然后重启了下 再运行 就
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/1e21ff4b-a3d3-4103-bd9f-1167efc7c888)

莫名其妙的就报错了

Traceback (most recent call last):
  File "D:\BL\BallonsTranslator\ballontrans_pylibs_win\lib\site-packages\py7zr\compressor.py", line 67, in <module>
    import brotli  # type: ignore  # noqa
  File "D:\BL\BallonsTranslator\ballontrans_pylibs_win\lib\site-packages\brotli.py", line 8, in <module>
    import _brotli
ImportError: DLL load failed while importing _brotli: %1 不是有效的 Win32 应用程序。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\BL\BallonsTranslator\launch.py", line 279, in <module>
    main()
  File "D:\BL\BallonsTranslator\launch.py", line 161, in main
    from modules.prepare_local_files import prepare_local_files_forall
  File "D:\BL\BallonsTranslator\modules\prepare_local_files.py", line 8, in <module>
    from utils.download_util import download_and_check_files
  File "D:\BL\BallonsTranslator\utils\download_util.py", line 17, in <module>
    from py7zr import pack_7zarchive, unpack_7zarchive
  File "D:\BL\BallonsTranslator\ballontrans_pylibs_win\lib\site-packages\py7zr\__init__.py", line 45, in <module>
    from py7zr.py7zr import ArchiveInfo, FileInfo, SevenZipFile, is_7zfile, pack_7zarchive, unpack_7zarchive
  File "D:\BL\BallonsTranslator\ballontrans_pylibs_win\lib\site-packages\py7zr\py7zr.py", line 44, in <module>
    from py7zr.archiveinfo import Folder, Header, SignatureHeader
  File "D:\BL\BallonsTranslator\ballontrans_pylibs_win\lib\site-packages\py7zr\archiveinfo.py", line 36, in <module>
    from py7zr.compressor import SevenZipCompressor, SevenZipDecompressor
  File "D:\BL\BallonsTranslator\ballontrans_pylibs_win\lib\site-packages\py7zr\compressor.py", line 69, in <module>
    import brotlicffi as brotli  # type: ignore  # noqa
ModuleNotFoundError: No module named 'brotlicffi'
请按任意键继续. . .

问了GPT 我也没看懂
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/de38ca15-01c5-441c-8890-6eb688d1be14)

**Comment by dmMaze** [comment]
试下装https://aka.ms/vs/17/release/vc_redist.x86.exe或者https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by lhj5426** [comment]
> 试下装
> 
> [https://aka.ms/vs/17/_release_/vc_redist.x64.exe](https://aka.ms/vs/17/release/vc_redist.x64.exe)* 或者 [https://aka.ms/vs/17/_release_/vc_redist.x64.exe](https://aka.ms/vs/17/release/vc_redist.x64.exe)*

![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/e9709262-3507-4c8e-91b7-fd04dc376fc2)

运行是这个提示 我
之前是 能运行的
我还给您 截图说
增加了一个新的 模型呢
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/a8c7aa02-633d-4795-8c76-8000958cf0e8)

结果 重启电脑就不行 报错了

**Comment by dmMaze** [comment]
你重启前是不是装了/卸载了什么东西？
那就按上面截图的做，卸载系统里的旧vcx64和x86重新装一下这俩

**Comment by lhj5426** [comment]
> 你重启前是不是装了/卸载了什么东西？ 那就按上面截图的做，卸载系统里的旧vcx64和x86重新装一下这俩

![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/3269621a-02c5-4238-b5d9-354f5b07f79b)
安装了 还是

**Comment by dmMaze** [comment]
> > 你重启前是不是装了/卸载了什么东西？ 那就按上面截图的做，卸载系统里的旧vcx64和x86重新装一下这俩
> 
> ![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/3269621a-02c5-4238-b5d9-354f5b07f79b)
> 安装了 还是

x86呢（刚才链接贴重了

**Comment by lhj5426** [comment]
> 你重启前是不是装了/卸载了什么东西？ 那就按上面截图的做，卸载系统里的旧vcx64和x86重新装一下这俩

![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/c6ac95a7-7213-413a-abef-c0b1c1f0e9e7)
我重启之后没有安装任何东西 就正常重启然后 运行软件和浏览器 过了一会发现软件弹出界面 一看就这报错。。

**Comment by dmMaze** [comment]
OK再试试更新到ca0aec8再跑下

**Comment by lhj5426** [comment]
> OK再试试更新到 [ca0aec8](https://github.com/dmMaze/BallonsTranslator/commit/ca0aec8fbeca1b3824d343b22595b9abaa8a7325) 再跑下

![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/13779303-89fe-4547-a558-4be1234b4c6d)
 热泪盈眶
 终于又见到界面了
 真的太感谢了

**Comment by lhj5426** [comment]
重启了一遍电脑 顺便识别了一本 应该是没毛病了 谢谢大佬
辛苦大佬了！！！！！
