### ISSUE TITLE
DEV版切换windows OCR报错

### ISSUE THREAD

**Issue by didala083** [dmMaze/BallonsTranslator#321]
一旦切换为windows OCR就会报错然后切换为前一个模型，报错信息如下：

Traceback (most recent call last):
  File "\BallonsTranslator\ui\module_manager.py", line 53, in _set_module
    self.module = module(**params)
  File "\BallonsTranslator\modules\ocr\__init__.py", line 27, in __init__
    self.setup_ocr()
  File "\BallonsTranslator\modules\ocr\__init__.py", line 367, in setup_ocr
    self.engine.lang = self.get_engine_lang()
  File "\soft\BallonsTranslator\modules\ocr\__init__.py", line 371, in get_engine_lang
    tag_name = languages_tag[languages_display_name.index(language)]
ValueError: '日语' is not in list

**Comment by bropines** [comment]
apparently you have something with Japanese, or rather it is not fully written

**Comment by dmMaze** [comment]
winocr 应该是要额外装语言包的 https://learn.microsoft.com/en-us/windows/powertoys/text-extractor#troubleshooting

**Comment by didala083** [comment]
感谢提醒，日语包确实没有装，这个可以关闭啦~
