### ISSUE TITLE
改字号的时候程序停止响应

### ISSUE THREAD

**Issue by didala083** [dmMaze/BallonsTranslator#343]
对其中某一个文字框更改字号的时候总会停止响应，每次都会复现
报错如下：

QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::pen: Painter not active
QPainter::setPen: Painter not active
QPainter::pen: Painter not active
QPainter::setPen: Painter not active
QPainter::setPen: Painter not active
QPainter::end: Painter not active, aborted
Traceback (most recent call last):
  File "J:\BallonsTranslator\ui\scene_textlayout.py", line 273, in documentChanged
    self.reLayout()
  File "J:\BallonsTranslator\ui\scene_textlayout.py", line 341, in reLayout
    self.updateDrawOffsets()
  File "J:\BallonsTranslator\ui\scene_textlayout.py", line 399, in updateDrawOffsets
    non_bracket_br = cfmt.punc_actual_rect(line, char, cache=True)
  File "J:\BallonsTranslator\ui\scene_textlayout.py", line 152, in punc_actual_rect
    ar = punc_actual_rect_cached(line, char, self.family, self.size, self.weight, self.font.italic(), stroke_width)
  File "J:\BallonsTranslator\ui\scene_textlayout.py", line 83, in punc_actual_rect_cached
    return punc_actual_rect(line.line, family, size, weight, italic, stroke_width)
  File "J:\BallonsTranslator\ui\scene_textlayout.py", line 67, in punc_actual_rect
    mask = pixmap2ndarray(pixmap, keep_alpha=True)[..., -1]
  File "J:\BallonsTranslator\ui\misc.py", line 36, in pixmap2ndarray
    byte_str = byte_str.tobytes()
AttributeError: 'NoneType' object has no attribute 'tobytes'

**Comment by didala083** [comment]
但是如果从下拉菜单中选字号就没这个问题

**Comment by dmMaze** [comment]
我没法复现，你需要确保源码是最新的，PyQt6-Qt6==6.4.2  PyQt6==6.4.2，如果已经是了可以录个视频给我看看

**Comment by didala083** [comment]
我重启下后又没有复现了，也不知道是怎么回事

**Comment by didala083** [comment]
https://github.com/dmMaze/BallonsTranslator/assets/64563710/db6da417-f681-46ec-a8ea-7394587eb344

终于等到复现了，提示的信息和之前的类似。

**Comment by dmMaze** [comment]
@didala083 我还是没法复现，方便的话你可以把这一页和项目文件打包发到我邮箱 [beneathlimbo@gmail.com](mailto:beneathlimbo@gmail.com)

**Comment by dmMaze** [comment]
6fca60b3c85c4da07d18cc432f3d0cf778d15380 应该修好了，有问题再开
