### ISSUE TITLE
python  at  翻译失敗: NotValidLength) 

### ISSUE THREAD

**Issue by ericshug** [dmMaze/BallonsTranslator#376]
用google翻译  出現 python  at  翻译失敗: NotValidLength) 

Traceback (most recent call last):
  File "C:\BallonsTranslator-1.4.0\ui\module_manager.py", line 232, in _run_translate_pipeline
    self._translate_page(self.imgtrans_proj.pages, page_key, raise_exception=True, emit_finished=False)
  File "C:\BallonsTranslator-1.4.0\ui\module_manager.py", line 203, in _translate_page
    raise e
  File "C:\BallonsTranslator-1.4.0\ui\module_manager.py", line 195, in _translate_page
    self.translator.translate_textblk_lst(page)
  File "C:\BallonsTranslator-1.4.0\modules\translators\base.py", line 197, in translate_textblk_lst
    _translations = self.translate(text_list)
  File "C:\BallonsTranslator-1.4.0\modules\translators\base.py", line 146, in translate
    text_trans = self._translate([text_source])[0]
  File "C:\BallonsTranslator-1.4.0\modules\translators\trans_google.py", line 315, in _translate
    translations = [self.googletrans.translate(t) for t in src_list]
  File "C:\BallonsTranslator-1.4.0\modules\translators\trans_google.py", line 315, in <listcomp>

**Comment by dmMaze** [comment]
log不完整，是不是这一页原文太长了
