### ISSUE TITLE
Issues building MacOS app

### ISSUE THREAD

**Issue by KamillaPup** [dmMaze/BallonsTranslator#378]
- Apple M3 Max
- 48 GB
- macOS 14.1

When running the build, I keep getting venv errors and not able to find python.

```cd /Users/user/Downloads/data 
user@Computer data % git clone -b dev https://github.com/dmMaze/BallonsTranslator.git
Cloning into 'BallonsTranslator'...
remote: Enumerating objects: 4922, done.
remote: Counting objects: 100% (967/967), done.
remote: Compressing objects: 100% (226/226), done.
remote: Total 4922 (delta 793), reused 761 (delta 741), pack-reused 3955
Receiving objects: 100% (4922/4922), 57.41 MiB | 29.59 MiB/s, done.
Resolving deltas: 100% (3567/3567), done.
user@Computer data % cd BallonsTranslator 
user@Computer BallonsTranslator % sh scripts/build-macos-app.sh
python-build: use openssl@3 from homebrew
python-build: use readline from homebrew
Downloading Python-3.11.5.tar.xz...
-> https://www.python.org/ftp/python/3.11.5/Python-3.11.5.tar.xz
Installing Python-3.11.5...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/user/.pyenv/versions/3.11.5/lib/python3.11/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
WARNING: The Python lzma extension was not compiled. Missing the lzma lib?
Installed Python-3.11.5 to /Users/user/.pyenv/versions/3.11.5
scripts/build-macos-app.sh: line 12: python: command not found
scripts/build-macos-app.sh: line 13: venv/bin/activate: No such file or directory```

I then tried running the commands in the macos-build script replacing python with python3 and it got threw it but then failed at the very end:
```(venv) user@Computer BallonsTranslator % sudo pyinstaller launch.spec
619 INFO: PyInstaller: 6.4.0, contrib hooks: 2024.1
619 INFO: Python: 3.9.6
626 INFO: Platform: macOS-14.1-arm64-arm-64bit
652 INFO: Extending PYTHONPATH with paths
['/Users/user/Downloads/data/BallonsTranslator',
 '/Users/user/Downloads/data/BallonsTranslator/scripts']
1758 INFO: Appending 'datas' from .spec
Unable to find '/Users/user/Downloads/data/BallonsTranslator/venv/lib/python3.11/site-packages/spacy_pkuseg' when adding binary and data files.```

**Comment by dmMaze** [comment]
Have you tried install ```spacy-pkuseg``` to the venv?
Besides according to the log installed venv py==3.11.5 while your PyInstaller py==3.9.6, I don't know if it matters since I haven't walked through those macos building steps myself. Besides you could run the source directly.

**Comment by KamillaPup** [comment]
I feel we are closer thanks to your advice to install spacy-pkuseg:
```user@Computer /Applications % /Applications/BallonsTranslator.app/Contents/MacOS/launch
py version:  3.9.6 (default, Nov 10 2023, 13:38:27) 
[Clang 15.0.0 (clang-1500.1.0.2.5)]
py executable:  /Applications/BallonsTranslator.app/Contents/MacOS/launch
version: 1.4.0
branch: dev
Commit hash: <none>
Running as app, skip dependency installation
Traceback (most recent call last):
  File "launch.py", line 274, in <module>
  File "launch.py", line 143, in main
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "utils/shared.py", line 20, in <module>
    os.makedirs(DEFAULT_TEXTSTYLE_DIR)
  File "os.py", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/Applications/BallonsTranslator.app/Contents/Frameworks/config/textstyles'
[63135] Failed to execute script 'launch' due to unhandled exception: [Errno 13] Permission denied: '/Applications/BallonsTranslator.app/Contents/Frameworks/config/textstyles'
[63135] Traceback:
Traceback (most recent call last):
  File "launch.py", line 274, in <module>
  File "launch.py", line 143, in main
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "utils/shared.py", line 20, in <module>
    os.makedirs(DEFAULT_TEXTSTYLE_DIR)
  File "os.py", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/Applications/BallonsTranslator.app/Contents/Frameworks/config/textstyles'```
I checked the config folder, and there is no file called `textstyles`

**Comment by dmMaze** [comment]
> PermissionError: [Errno 13] Permission denied: '/Applications/BallonsTranslator.app/Contents/Frameworks/config/textstyles'

Grant write permission to the app, or move it to somewhere it has write permission

**Comment by notjl** [comment]
I'm having the same issue, I've already granted write permission to the app or even moving it to Desktop and Applications. It still won't open because it's having the same error wherein `textstyles` cannot be found. I tried building the app where I granted the write permission and it still won't work.
