### ISSUE TITLE
安裝時發生錯誤

### ISSUE THREAD

**Issue by TTUGrice** [dmMaze/BallonsTranslator#402]
錯誤資訊
ImportError: cannot import name 'is_arabic' from 'charset_normalizer.utils' 

請問我該如何修復它?

**Comment by TTUGrice** [comment]
更新一下完整的log

E:\BallonTranslator\BallonsTranslator_dev_src_with_gitpython>cd E:\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\
E:\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\launch.py:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
py version:  3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
py executable:  E:\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\python.exe
version: 1.4.0
branch: dev
Commit hash: 00b3896679a89a4c27fe06511cde7a294e41c7e1
Traceback (most recent call last):
  File "E:\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\lib\site-packages\requests\compat.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\launch.py", line 273, in <module>
    main()
  File "E:\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\launch.py", line 149, in main
    from utils import config as program_config
  File "E:\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\utils\config.py", line 8, in <module>
    from .io_utils import json_dump_nested_obj
  File "E:\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\utils\io_utils.py", line 9, in <module>
    import requests
  File "E:\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\lib\site-packages\requests\__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "E:\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\lib\site-packages\requests\exceptions.py", line 9, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "E:\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\lib\site-packages\requests\compat.py", line 13, in <module>
    import charset_normalizer as chardet
  File "E:\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\lib\site-packages\charset_normalizer\__init__.py", line 24, in <module>
    from .api import from_bytes, from_fp, from_path, normalize
  File "E:\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\lib\site-packages\charset_normalizer\api.py", line 7, in <module>
    from .cd import (
  File "E:\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\lib\site-packages\charset_normalizer\cd.py", line 9, in <module>
    from .md import is_suspiciously_successive_range
  File "charset_normalizer\md.py", line 10, in <module>
ImportError: cannot import name 'is_arabic' from 'charset_normalizer.utils' (E:\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\lib\site-packages\charset_normalizer\utils.py)

**Comment by dmMaze** [comment]
BallonsTranslator_dev_src_with_gitpython 这个目录下的python是你自己下了塞进去的？这个包不需要额外下python，我建议你重新解压出一个**干净**的 BallonsTranslator_dev_src_with_gitpython 然后直接运行launch_win.bat
