### ISSUE TITLE
Library cublas64_12.dll is not found or cannot be loaded

### ISSUE THREAD

**Issue by simonrule** [dmMaze/BallonsTranslator#404]
can anyone help me fix this issue please, i get it when i use sugio translator?

Library cublas64_12.dll is not found or cannot be loaded

> Traceback (most recent call last):
  File "C:\Users\simon\Desktop\BallonsTranslator_dev_src_with_gitpython\ui\module_manager.py", line 471, in run
    self.job()
  File "C:\Users\simon\Desktop\BallonsTranslator_dev_src_with_gitpython\ui\module_manager.py", line 427, in _imgtrans_pipeline
    self.translator.translate_textblk_lst(blk_list)
  File "C:\Users\simon\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\base.py", line 198, in translate_textblk_lst
    _translations = self.translate(text_list)
  File "C:\Users\simon\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\base.py", line 145, in translate
    text_trans = self._translate(text_source)
  File "C:\Users\simon\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_sugoi.py", line 25, in _translate
    tokenized_translated = self.translator.translate_batch(tokenized_text)
RuntimeError: Library cublas64_12.dll is not found or cannot be loaded

**Comment by dmMaze** [comment]
https://github.com/Pikurrot/whisper-gui/issues/15#issuecomment-1967495483
Downgrade  your ctranslate2 < 4.0.0, or upgrade your cuda to 12.x

**Comment by simonrule** [comment]
> [Pikurrot/whisper-gui#15 (comment)](https://github.com/Pikurrot/whisper-gui/issues/15#issuecomment-1967495483) Downgrade your ctranslate2 < 4.0.0, or upgrade your cuda to 12.x

thank you so much, worked perfectly
