### ISSUE TITLE
运行launch_win.bat時出現ImportError 无法启动

### ISSUE THREAD

**Issue by Kuro-Bit** [dmMaze/BallonsTranslator#419]
C:\Program Files\BallonsTranslator_dev_src_with_gitpython>cd C:\Program Files\BallonsTranslator_dev_src_with_gitpython\
C:\Program Files\BallonsTranslator_dev_src_with_gitpython\launch.py:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
py version:  3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
py executable:  C:\Program Files\BallonsTranslator_dev_src_with_gitpython\ballontrans_pylibs_win\python.exe
version: 1.4.0
branch: dev
Commit hash: 5d7aec993a9fc60bd954cb0168d902fd2ef642ca
Traceback (most recent call last):
  File "C:\Program Files\BallonsTranslator_dev_src_with_gitpython\launch.py", line 285, in <module>
    main()
  File "C:\Program Files\BallonsTranslator_dev_src_with_gitpython\launch.py", line 152, in main
    from utils import config as program_config
  File "C:\Program Files\BallonsTranslator_dev_src_with_gitpython\utils\config.py", line 5, in <module>
    from .fontformat import FontFormat
  File "C:\Program Files\BallonsTranslator_dev_src_with_gitpython\utils\fontformat.py", line 3, in <module>
    from .textblock import TextBlock
  File "C:\Program Files\BallonsTranslator_dev_src_with_gitpython\utils\textblock.py", line 6, in <module>
    import cv2
  File "C:\Program Files\BallonsTranslator_dev_src_with_gitpython\ballontrans_pylibs_win\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Program Files\BallonsTranslator_dev_src_with_gitpython\ballontrans_pylibs_win\lib\site-packages\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "importlib\__init__.py", line 126, in import_module
    if sys.path[0] == BASE_DIR or os.path.realpath(sys.path[0]) == BASE_DIR:
ImportError: DLL load failed while importing cv2: The specified module could not be found.
Press any key to continue . . .

请问我是少安装了什么程序或是什么步骤呢？

**Comment by dmMaze** [comment]
试试装这条提到的两个库
https://stackoverflow.com/a/58699644
