### ISSUE TITLE
ModuleNotFoundError: No module named 'termcolor'

### ISSUE THREAD

**Issue by weiyihueng0219** [dmMaze/BallonsTranslator#497]
I don't how to resolve this problem maybe I'm too stupid 

C:\Users\weiyihuang\Desktop\BallonsTranslator_dev_src_with_gitpython>cd C:\Users\weiyihuang\Desktop\BallonsTranslator_dev_src_with_gitpython\
C:\Users\weiyihuang\Desktop\BallonsTranslator_dev_src_with_gitpython\launch.py:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Traceback (most recent call last):
  File "C:\Users\weiyihuang\Desktop\BallonsTranslator_dev_src_with_gitpython\launch.py", line 290, in <module>
    main()
  File "C:\Users\weiyihuang\Desktop\BallonsTranslator_dev_src_with_gitpython\launch.py", line 141, in main
    from utils import appinfo
  File "C:\Users\weiyihuang\Desktop\BallonsTranslator_dev_src_with_gitpython\utils\__init__.py", line 5, in <module>
    from .logger import logger as LOGGER
  File "C:\Users\weiyihuang\Desktop\BallonsTranslator_dev_src_with_gitpython\utils\logger.py", line 6, in <module>
    import termcolor
ModuleNotFoundError: No module named 'termcolor'

**Comment by dmMaze** [comment]
It should be fixed by https://github.com/dmMaze/BallonsTranslator/commit/64573f6777d8d1745b4b908aabcc2cb2c2db2c03 
Please update to the latest and try again.
