### ISSUE TITLE
新版本不再支持win7了么

### ISSUE THREAD

**Issue by qwea12c** [dmMaze/BallonsTranslator#507]
以前用1.3 1.2版本还可以win7下使用 今天升级了1.4发现不支持了
现在想找一个win7能用的工具越来越少了

**Comment by dmMaze** [comment]
我没试过，手边也没设备，不过应该是可以的。需要自己配置一下环境，用 **python 3.8**

**Comment by dmMaze** [comment]
好吧，应该是不行，Qt6 就不支持 win7 了

**Comment by qwea12c** [comment]
> 好吧，应该是不行，Qt6 就不支持 win7 了

我看到需要Qt6就感觉没戏了orz 那么请问一下最后可能支持win7的版本是多少

**Comment by qwea12c** [comment]
> @qwea12c Qt5 也能跑，自己配置一下 python3.8，拉一下最新源码，然后运行 launch_win.bat

下载了你最新的版本
然后运行后报错误
D:\Program\BallonsTranslator-dev>cd D:\Program\BallonsTranslator-dev\
py version:  3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64
 bit (AMD64)]
py executable:  C:\Program Files\Python38\python38.exe
version: 1.4.0
branch: dev
Commit hash: <none>
Traceback (most recent call last):
  File "launch.py", line 296, in <module>
    main()
  File "launch.py", line 161, in main
    from qtpy.QtCore import QTranslator, QLocale, Qt
  File "C:\Program Files\Python38\lib\site-packages\qtpy\__init__.py", line 287,
 in <module>
    raise QtBindingsNotFoundError from None
qtpy.QtBindingsNotFoundError: No Qt bindings could be found


然后我自己搜索了下装了win7也能运行的PYSIDE6版本后 报错
D:\Program\BallonsTranslator-dev>cd D:\Program\BallonsTranslator-dev\
py version:  3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64
 bit (AMD64)]
py executable:  C:\Program Files\Python38\python38.exe
version: 1.4.0
branch: dev
Commit hash: <none>
launch.py:161: PythonQtWarning: Selected binding 'pyqt6' could not be found; fal
ling back to 'pyside6'
  from qtpy.QtCore import QTranslator, QLocale, Qt
C:\Program Files\Python38\lib\site-packages\qtpy\__init__.py:327: PythonQtWarnin
g: Qt6 version 6.1.3 is not supported by QtPy. To ensure your application works
correctly with QtPy, please upgrade to Qt6 6.2.0 or later.
  _warn_old_minor_version("Qt6", QT_VERSION, QT6_VERSION_MIN)
C:\Program Files\Python38\lib\site-packages\qtpy\__init__.py:338: PythonQtWarnin
g: PySide6 version 6.1.3 is not supported by QtPy. To ensure your application wo
rks correctly with QtPy, please upgrade to PySide6 6.2.0 or later.
  _warn_old_minor_version("PySide6", PYSIDE_VERSION, PYSIDE6_VERSION_MIN)
[INFO   ] config:load_config:188 - D:\Program\BallonsTranslator-dev\config/confi
g.json does not exist, new config file will be created.
[INFO   ] launch:main:182 - QT_API: pyside6, QT Version: 6.1.3
Traceback (most recent call last):
  File "launch.py", line 296, in <module>
    main()
  File "launch.py", line 198, in main
    load_modules()
  File "launch.py", line 125, in load_modules
    _load_module(**kwargs)
  File "launch.py", line 117, in _load_module
    importlib.import_module(module_path + module_name.replace('.py', ''))
  File "C:\Program Files\Python38\lib\importlib\__init__.py", line 127, in impor
t_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Program\BallonsTranslator-dev\modules\translators\trans_chatgpt.py",
line 9, in <module>
    import openai
  File "C:\Program Files\Python38\lib\site-packages\openai\__init__.py", line 8,
 in <module>
    from . import types
  File "C:\Program Files\Python38\lib\site-packages\openai\types\__init__.py", l
ine 5, in <module>
    from .batch import Batch as Batch
  File "C:\Program Files\Python38\lib\site-packages\openai\types\batch.py", line
 7, in <module>
    from .._models import BaseModel
  File "C:\Program Files\Python38\lib\site-packages\openai\_models.py", line 23,
 in <module>
    from pydantic.fields import FieldInfo
  File "C:\Program Files\Python38\lib\site-packages\pydantic\fields.py", line 17
, in <module>
    from pydantic_core import PydanticUndefined
  File "C:\Program Files\Python38\lib\site-packages\pydantic_core\__init__.py",
line 6, in <module>
    from ._pydantic_core import (
ImportError: DLL load failed while importing _pydantic_core: 找不到指定的程序。
请按任意键继续. . .

然后问了问ai 更新了下openai库和pydantic 问题依旧

搞不定了 5555

**Comment by qwea12c** [comment]
额直接发代码 site-packages\pydantic_core\__init__.py 就会变成site-packages\pydantic_core_init.py
一个\和_消失了

**Comment by dmMaze** [comment]
@qwea12c 你不需要自己装 pyqt 或者 pyside 啊。有 python 环境不用自己装任何包直接跑 launch_win.bat 应该就会根据你系统装 pyqt5 和其它包了。
另外你系统是 64位的吗？
我建议把现在这个 python 版本删干净，装一个版本对的 python3.8，升级一下 pip: `python -m pip install ––upgrade pip`，然后直接跑程序

**Comment by dmMaze** [comment]
@qwea12c 如果直接运行没装 PyQt5 就自己装一下
```
pip install PyQt5-Qt5>=5.15.2
```

**Comment by qwea12c** [comment]
> @qwea12c 如果直接运行没装 PyQt5 就自己装一下
> 
> ```
> pip install PyQt5-Qt5>=5.15.2
> ```

我发现qt5那个问题所在了 我这电脑用的是windows2008r2也就是win7的服务器版 launch.py里只写了win7的时候用qt5 

修改成任何时候都用qt5后还是爆错 我试了在win7x64虚拟机下ballonstranslator不去改动任何内容 就装一个全新的py3.8.10也是同样的报错  我电脑是amd furyx显卡 不是n卡不支持cuda
![1](https://github.com/dmMaze/BallonsTranslator/assets/78415898/db5ad617-3160-4606-a156-9ec47131b031)
之后我试了下把torch从version__ = '2.3.1+cu118'换成version__ = '2.3.1+cpu' 报的错误就成了
![QQ图片20240705230747](https://github.com/dmMaze/BallonsTranslator/assets/78415898/490f41e0-03f1-4633-aaad-ba1a41ea8389)

**Comment by dmMaze** [comment]
@qwea12c 
pydantic 报错可以试试 https://github.com/pydantic/pydantic/issues/6557#issuecomment-1935336347
或者删掉 ```modules\translators\trans_chatgpt.py```
