### ISSUE TITLE
無法啓動

### ISSUE THREAD

**Issue by Raiter123** [dmMaze/BallonsTranslator#528]
非常抱歉,我的氣球又在出問題了,我是現在無法啓動,是因爲我更新到不該更新的東西嗎?
![image](https://github.com/user-attachments/assets/72bdcb75-2a76-4c2a-bcb7-fddbe2571910)

C:\Users\User-PC\BallonsTranslator>cd C:\Users\User-PC\BallonsTranslator\
C:\Users\User-PC\BallonsTranslator\launch.py:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
py version:  3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
py executable:  C:\Users\User-PC\AppData\Local\Programs\Python\Python310\python.exe
version: 1.4.0
branch: dev
Commit hash: 068a5fd439c472886219d7e287c5435f365bb81f
[INFO   ] launch:main:184 - QT_API: pyqt6, QT Version: 6.6.1
Traceback (most recent call last):
  File "C:\Users\User-PC\BallonsTranslator\launch.py", line 307, in <module>
    main()
  File "C:\Users\User-PC\BallonsTranslator\launch.py", line 200, in main
    load_modules()
  File "C:\Users\User-PC\BallonsTranslator\launch.py", line 126, in load_modules
    _load_module(**kwargs)
  File "C:\Users\User-PC\BallonsTranslator\launch.py", line 118, in _load_module
    importlib.import_module(module_path + module_name.replace('.py', ''))
  File "C:\Users\User-PC\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\User-PC\BallonsTranslator\modules\__init__.py", line 1, in <module>
    from .ocr import OCR, OCRBase
  File "C:\Users\User-PC\BallonsTranslator\modules\ocr\__init__.py", line 1, in <module>
    from .base import OCRBase, register_OCR, DEVICE_SELECTOR, DEFAULT_DEVICE, TextBlock, OCR
  File "C:\Users\User-PC\BallonsTranslator\modules\ocr\base.py", line 11, in <module>
    from ..base import BaseModule, DEFAULT_DEVICE, DEVICE_SELECTOR, LOGGER
  File "C:\Users\User-PC\BallonsTranslator\modules\base.py", line 147, in <module>
    import torch
  File "C:\Users\User-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\User-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
Press any key to continue . . .

**Comment by bropines** [comment]
Install an older pytorch

**Comment by Raiter123** [comment]
> Install an older pytorch安装较旧的 pytorch
> 
> ```shell
> pip install torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu118
> ```

still the same

**Comment by bropines** [comment]
> > Install an older pytorch安装较旧的 pytorch
> > ```shell
> > pip install torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu118
> > ```
> 
> still the same ![image](https://private-user-images.githubusercontent.com/153535038/355112566-c85edfd2-d820-4307-81e5-f9d06aabbb2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODg5MjIsIm5iZiI6MTcyMjg4ODYyMiwicGF0aCI6Ii8xNTM1MzUwMzgvMzU1MTEyNTY2LWM4NWVkZmQyLWQ4MjAtNDMwNy04MWU1LWY5ZDA2YWFiYmIyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQyMDEwMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTJhNzAwODQwNmEwNjJhNGYwYzdjMjkyZGNkYzJiNTcxNzBiMWQxYmM3OGM0YmZiNjgxYmQyNmQzMjE0YjU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WCXJ8r9U7hvtZK3XVqcSGGkoQDQBZC63Gm2aLvlD-cE)

naturally. you probably just wanted to install it on command, but you need to reinstall it. Sorry, here's a normal command. Try it
```bash
pip3 install --upgrade --force-reinstall torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```

**Comment by bropines** [comment]
Work? @Raiter123

**Comment by Raiter123** [comment]
> Work? @Raiter123 工作？@Raiter123

done
