### ISSUE TITLE
修復好像出現問題

### ISSUE THREAD

**Issue by Raiter123** [dmMaze/BallonsTranslator#569]
修復好像出現問題
![image](https://github.com/user-attachments/assets/a14952b9-89e4-4870-bfea-117aff50ed5c)

Traceback (most recent call last):
  File "C:\Users\User-PC\BallonsTranslator 2\ui\module_manager.py", line 440, in _imgtrans_pipeline
    inpainted = self.inpainter.inpaint(img, mask, blk_list)
  File "C:\Users\User-PC\BallonsTranslator 2\modules\inpaint\base.py", line 107, in inpaint
    inpainted[xyxy_e[1]:xyxy_e[3], xyxy_e[0]:xyxy_e[2]] = self.memory_safe_inpaint(im, msk)
  File "C:\Users\User-PC\BallonsTranslator 2\modules\inpaint\base.py", line 58, in memory_safe_inpaint
    raise e
  File "C:\Users\User-PC\BallonsTranslator 2\modules\inpaint\base.py", line 39, in memory_safe_inpaint
    return self._inpaint(img, mask, textblock_list)
  File "C:\Users\User-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\User-PC\BallonsTranslator 2\modules\inpaint\base.py", line 355, in _inpaint
    img_torch, mask_torch, rel_pos, direct, img_original, mask_original, pad_bottom, pad_right = self.inpaint_preprocess(img, mask)
  File "C:\Users\User-PC\BallonsTranslator 2\modules\inpaint\base.py", line 344, in inpaint_preprocess
    img_torch = img_torch.to(self.device)
RuntimeError: PyTorch is not linked with support for mps devices

**Comment by dmMaze** [comment]
设置里，device 不该选 mps，这是 mac 用的
