### ISSUE TITLE
Failed to set manga_ocr:No module named 'asyncio' K Show Details...

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#57]
![image](https://user-images.githubusercontent.com/30548000/204570770-8ed669d5-5c36-4416-980e-198303395f2c.png)
![image](https://user-images.githubusercontent.com/30548000/204570839-ef75059c-f1fd-41fc-999b-ea9f967aa976.png)

![image](https://user-images.githubusercontent.com/30548000/204569920-9fb0d006-5d88-4ad8-a5f9-f8bc9c83116d.png)

Traceback (most recent call last):
  File "D:\BALLON~1\ui\dl_manager.py", line 47, in _set_module
  File "D:\BALLON~1\dl\ocr\__init__.py", line 22, in __init__
  File "D:\BALLON~1\dl\ocr\__init__.py", line 125, in setup_ocr
  File "D:\BALLON~1\dl\ocr\manga_ocr.py", line 4, in <module dl.ocr.manga_ocr>
  File "D:\BallonTranslator\transformers\__init__.py", line 31, in <module>
    from .file_utils import (
  File "D:\BallonTranslator\transformers\file_utils.py", line 51, in <module>
    from huggingface_hub import HfFolder, Repository, create_repo, list_repo_files, whoami
  File "D:\BallonTranslator\huggingface_hub\__init__.py", line 33, in <module>
    from .file_download import cached_download, hf_hub_download, hf_hub_url
  File "D:\BallonTranslator\huggingface_hub\file_download.py", line 16, in <module>
    from tqdm.auto import tqdm
  File "D:\BallonTranslator\tqdm\auto.py", line 29, in <module>
    from .asyncio import tqdm as asyncio_tqdm
  File "D:\BallonTranslator\tqdm\asyncio.py", line 10, in <module>
    import asyncio
ModuleNotFoundError: No module named 'asyncio'
因为识别不准确且不能单独进行框选识别 我打算换个引擎然后重新跑
被提示这个 是需要下载什么东西吗？

**Comment by dmMaze** [comment]
有两个包没传, 请更新至1.3.16

**Comment by lhj5426** [comment]
> 有两个包没传, 请更新至1.3.16

感谢 好像好了没有再报这个错误了

**Comment by TwilightHome20** [comment]
![image](https://user-images.githubusercontent.com/101049847/204835490-300c6047-351f-4607-a392-3cfa0088d939.png)
更新以后使用manga_ocr会造成闪退

**Comment by TwilightHome20** [comment]
呃....很奇怪,在重启电脑后错误消失了,可以正常使用了,谢谢大佬,顺便问下有没有赞助咖啡的渠道🤣👍

> > ![image](https://user-images.githubusercontent.com/101049847/204835490-300c6047-351f-4607-a392-3cfa0088d939.png)
> > 更新以后使用manga_ocr会造成闪退,在选择并运行后
> 
> 我无法复现，你是某张特定图片出问题还是怎么回事...如果是方便的话分享一下原图
