### ISSUE TITLE
Sugoi translator not working on Windows

### ISSUE THREAD

**Issue by Vortexakhaj** [dmMaze/BallonsTranslator#589]
[INFO   ] module_manager:on_finish_settranslator:917 - Translator set to Sugoi
[INFO   ] config:save_config:216 - Config saved
Traceback (most recent call last):
  File "E:\Image Translator\BallonsTranslator\BallonsTranslator_dev_src_with_gitpython\ui\module_manager.py", line 486, in run
    self.job()
  File "E:\Image Translator\BallonsTranslator\BallonsTranslator_dev_src_with_gitpython\ui\module_manager.py", line 431, in _imgtrans_pipeline
    self.translator.translate_textblk_lst(blk_list)
  File "E:\Image Translator\BallonsTranslator\BallonsTranslator_dev_src_with_gitpython\modules\translators\base.py", line 205, in translate_textblk_lst
    _translations = self.translate(text_list)
  File "E:\Image Translator\BallonsTranslator\BallonsTranslator_dev_src_with_gitpython\modules\translators\base.py", line 149, in translate
    text_trans = self._translate(text_source)
  File "E:\Image Translator\BallonsTranslator\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_sugoi.py", line 25, in _translate
    tokenized_translated = self.translator.translate_batch(tokenized_text)
### RuntimeError: Library cublas64_12.dll is not found or cannot be loaded

**Comment by bropines** [comment]
Try this
```bash
# CUDA 11.8
pip install -U torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu118
# CUDA 12.1
pip install -U torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu121
```

**Comment by seth-rah** [comment]
Had the same on my end and ran the commands

No luck from my end

```
Traceback (most recent call last):
  File "G:\Public Git Clones\BallonsTranslator_dev_src_with_gitpython\ui\module_manager.py", line 486, in run
    self.job()
  File "G:\Public Git Clones\BallonsTranslator_dev_src_with_gitpython\ui\module_manager.py", line 431, in _imgtrans_pipeline
    self.translator.translate_textblk_lst(blk_list)
  File "G:\Public Git Clones\BallonsTranslator_dev_src_with_gitpython\modules\translators\base.py", line 208, in translate_textblk_lst
    _translations = self.translate(text_list)
  File "G:\Public Git Clones\BallonsTranslator_dev_src_with_gitpython\modules\translators\base.py", line 149, in translate
    text_trans = self._translate(text_source)
  File "G:\Public Git Clones\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_sugoi.py", line 25, in _translate
    tokenized_translated = self.translator.translate_batch(tokenized_text)
RuntimeError: Library cublas64_12.dll is not found or cannot be loaded
```

My config.json for the model is still default though, is there a change needed here?

```
{
    "add_source_bos": false,
    "add_source_eos": true,
    "bos_token": "<s>",
    "decoder_start_token": "</s>",
    "eos_token": "</s>",
    "layer_norm_epsilon": null,
    "multi_query_attention": false,
    "unk_token": "<unk>"
  }
```

Probably also relevant

```
NVIDIA-SMI 572.47                 Driver Version: 572.47         CUDA Version: 12.8
```

**Comment by seth-rah** [comment]
Not impossible that windows can't be supported right now

https://forums.developer.nvidia.com/t/does-nvidia-give-up-the-development-of-hpc-sdk-on-windows-completely/316530

**Comment by bropines** [comment]
> Not impossible that windows can't be supported right now
> 
> [forums.developer.nvidia.com/t/does-nvidia-give-up-the-development-of-hpc-sdk-on-windows-completely/316530](https://forums.developer.nvidia.com/t/does-nvidia-give-up-the-development-of-hpc-sdk-on-windows-completely/316530)

It works for me. Have you installed nvidia toolkit? 

![Image](https://github.com/user-attachments/assets/fdd35cb9-b83c-42d4-8670-c3b117091ece)

**Comment by seth-rah** [comment]
That might be it. I was looking up the files and came across this link that only had linux installations

https://developer.nvidia.com/hpc-sdk-downloads

let me try that

**Comment by bropines** [comment]
https://developer.nvidia.com/cuda-downloads

?

**Comment by seth-rah** [comment]
There we go

Installed it, had to get one from the archive as the latest version seems to have installation issues with getting stuck during installation.

But I managed to run the translator :) 

Is there a readme I should have followed to get this operational first? As I was looking for documentation and eventually stumbled upon this thread while trying to debug.

**Comment by bropines** [comment]
> There we go
> 
> Installed it, had to get one from the archive as the latest version seems to have installation issues with getting stuck during installation.
> 
> But I managed to run the translator :)
> 
> Is there a readme I should have followed to get this operational first? As I was looking for documentation and eventually stumbled upon this thread while trying to debug.

I'll add translators to the documentation, it's important for me to know if nvidia toolkit or hpc helped you?

https://github.com/dmMaze/BallonsTranslator/blob/dev/doc/modules/translators.md#sakura

**Comment by seth-rah** [comment]
NVIDIA Toolkit

HPC isn't available for windows (yet) unfortunately 

The link you shared should be fine after Nvidia updates to a new release that doesn't stall during the installation process, because I had to pull 12.6 from the archive.

**Comment by bropines** [comment]
> NVIDIA Toolkit
> 
> HPC isn't available for windows (yet) unfortunately
> 
> The link you shared should be fine after Nvidia updates to a new release that doesn't stall during the installation process, because I had to pull 12.6 from the archive.

I'll add this to the documentation. Thanks
