### ISSUE TITLE
用带环境的包，下载安装完后无法启动，直接用网盘里的python包也不行

### ISSUE THREAD

**Issue by XiaoHaoJun** [dmMaze/BallonsTranslator#597]
D:\App\BallonsTranslator_dev_src_with_gitpython>cd D:\App\BallonsTranslator_dev_src_with_gitpython\
D:\App\BallonsTranslator_dev_src_with_gitpython\launch.py:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
py version:  3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
py executable:  D:\App\BallonsTranslator_dev_src_with_gitpython\ballontrans_pylibs_win\python.exe
version: 1.4.0
branch: dev
Commit hash: 0e9f40cdfd6f8d41d0f8682b0906147bb348ed2e
[INFO   ] config:load_config:193 - D:\App\BallonsTranslator_dev_src_with_gitpython\config/config.json does not exist, new config file will be created.
[INFO   ] launch:main:184 - QT_API: pyqt6, QT Version: 6.6.1
Traceback (most recent call last):
  File "D:\App\BallonsTranslator_dev_src_with_gitpython\launch.py", line 309, in <module>
    main()
  File "D:\App\BallonsTranslator_dev_src_with_gitpython\launch.py", line 200, in main
    load_modules()
  File "D:\App\BallonsTranslator_dev_src_with_gitpython\launch.py", line 126, in load_modules
    _load_module(**kwargs)
  File "D:\App\BallonsTranslator_dev_src_with_gitpython\launch.py", line 118, in _load_module
    importlib.import_module(module_path + module_name.replace('.py', ''))
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\App\BallonsTranslator_dev_src_with_gitpython\modules\ocr\ocr_windows.py", line 28, in <module>
    winocr_available_recognizer_languages = get_supported_language_packs()
  File "D:\App\BallonsTranslator_dev_src_with_gitpython\modules\ocr\ocr_windows.py", line 17, in get_supported_language_packs
    return list(OcrEngine.available_recognizer_languages)
OSError: [WinError -2147221164] 没有注册类
[INFO   ] utils:dump_compile_times:302 - TorchDynamo compilation metrics:
Function, Runtimes (s)
[INFO   ] utils:dump_compile_times:302 - TorchDynamo compilation metrics:
Function, Runtimes (s)
[2024-09-22 22:42:08,304] torch._dynamo.utils: [INFO] TorchDynamo compilation metrics:
[2024-09-22 22:42:08,304] torch._dynamo.utils: [INFO] Function, Runtimes (s)

**Comment by dmMaze** [comment]
用刚刚传网盘的包。或者装一下 windows OCR 的包：
https://learn.microsoft.com/zh-cn/windows/powertoys/text-extractor

**Comment by XiaoHaoJun** [comment]
> 用刚刚传网盘的包。或者装一下 windows OCR 的包： https://learn.microsoft.com/zh-cn/windows/powertoys/text-extractor

可以了谢谢，忘记之前装系统给ocr精简了
