### ISSUE TITLE
launch_win.bat shows errors

### ISSUE THREAD

**Issue by Aweirdkid69** [dmMaze/BallonsTranslator#618]
**When im trying to launch the program "launch_win.bat" it shows some issues, i've done everything like said in the github but when im trying to launch it shows me errors, does anyone know how to fix it :**

```
C:\ALL\APPS\all\work\Ballon translator\BallonTranslator-20241014T141350Z-001\BallonTranslator\BallonsTranslator_dev_src_with_gitpython>cd C:\ALL\APPS\all\work\Ballon translator\BallonTranslator-20241014T141350Z-001\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\
C:\ALL\APPS\all\work\Ballon translator\BallonTranslator-20241014T141350Z-001\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\launch.py:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
py version:  3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
py executable:  C:\ALL\APPS\all\work\Ballon translator\BallonTranslator-20241014T141350Z-001\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\ballontrans_pylibs_win\python.exe
version: 1.4.0
branch: dev
Commit hash: 0e05f8750a5993c38e5a4f648ad3ed5f8e373af7
[INFO   ] config:load_config:193 - C:\ALL\APPS\all\work\Ballon translator\BallonTranslator-20241014T141350Z-001\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\config/config.json does not exist, new config file will be created.
[INFO   ] launch:main:184 - QT_API: pyqt6, QT Version: 6.6.1
Traceback (most recent call last):
  File "C:\ALL\APPS\all\work\Ballon translator\BallonTranslator-20241014T141350Z-001\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\ballontrans_pylibs_win\lib\site-packages\transformers\__init__.py", line 3951, in <module>
    raise OptionalDependencyNotAvailable()
transformers.utils.import_utils.OptionalDependencyNotAvailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ALL\APPS\all\work\Ballon translator\BallonTranslator-20241014T141350Z-001\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\launch.py", line 309, in <module>
    main()
  File "C:\ALL\APPS\all\work\Ballon translator\BallonTranslator-20241014T141350Z-001\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\launch.py", line 200, in main
    load_modules()
  File "C:\ALL\APPS\all\work\Ballon translator\BallonTranslator-20241014T141350Z-001\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\launch.py", line 126, in load_modules
    _load_module(**kwargs)
  File "C:\ALL\APPS\all\work\Ballon translator\BallonTranslator-20241014T141350Z-001\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\launch.py", line 118, in _load_module
    importlib.import_module(module_path + module_name.replace('.py', ''))
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ALL\APPS\all\work\Ballon translator\BallonTranslator-20241014T141350Z-001\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\modules\ocr\ocr_manga.py", line 4, in <module>
    from transformers import AutoFeatureExtractor, AutoTokenizer, VisionEncoderDecoderModel
  File "C:\ALL\APPS\all\work\Ballon translator\BallonTranslator-20241014T141350Z-001\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\ballontrans_pylibs_win\lib\site-packages\transformers\__init__.py", line 3953, in <module>
    from .utils import dummy_essentia_and_librosa_and_pretty_midi_and_scipy_and_torch_objects
ImportError: cannot import name 'dummy_essentia_and_librosa_and_pretty_midi_and_scipy_and_torch_objects' from 'transformers.utils' (C:\ALL\APPS\all\work\Ballon translator\BallonTranslator-20241014T141350Z-001\BallonTranslator\BallonsTranslator_dev_src_with_gitpython\ballontrans_pylibs_win\lib\site-packages\transformers\utils\__init__.py)
[INFO   ] utils:dump_compile_times:247 - TorchDynamo compilation metrics:
Function, Runtimes (s)
[INFO   ] utils:dump_compile_times:247 - TorchDynamo compilation metrics:
Function, Runtimes (s)
[2024-10-14 21:24:24,063] torch._dynamo.utils: [INFO] TorchDynamo compilation metrics:
[2024-10-14 21:24:24,063] torch._dynamo.utils: [INFO] Function, Runtimes (s)
Press any key to continue . . .
```

https://github.com/user-attachments/assets/a464d651-d9cc-44a9-91c9-b7b7ba516dfb

https://github.com/user-attachments/assets/29261786-bd72-4c54-a0b1-2511d0d3e051

**Comment by Aweirdkid69** [comment]
Fixed.
