### ISSUE TITLE
大佬请问下安装报错这个是啥问题？

### ISSUE THREAD

**Issue by 733man** [dmMaze/BallonsTranslator#624]
PS E:\N_m3u8DL-CLI\python3.12.4> E:\N_m3u8DL-CLI\python3.12.4\BallonsTranslator\launch.py
E:\N_m3u8DL-CLI\python3.12.4\BallonsTranslator\launch.py:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
py version:  3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]
py executable:  E:\N_m3u8DL-CLI\python3.12.4\python.exe
version: 1.4.0
branch: dev
Commit hash: <none>
Traceback (most recent call last):
  File "E:\N_m3u8DL-CLI\python3.12.4\BallonsTranslator\launch.py", line 309, in <module>
    main()
  File "E:\N_m3u8DL-CLI\python3.12.4\BallonsTranslator\launch.py", line 160, in main
    from utils.io_utils import find_all_files_recursive
  File "E:\N_m3u8DL-CLI\python3.12.4\BallonsTranslator\utils\io_utils.py", line 9, in <module>
    import requests
  File "E:\N_m3u8DL-CLI\python3.12.4\Lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "E:\N_m3u8DL-CLI\python3.12.4\Lib\site-packages\urllib3\__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "E:\N_m3u8DL-CLI\python3.12.4\Lib\site-packages\urllib3\connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "E:\N_m3u8DL-CLI\python3.12.4\Lib\site-packages\urllib3\exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

**Comment by aqssxlzc** [comment]
用python3.10来启动吧

**Comment by rinhon** [comment]
```bash
(venv) PS C:\code\BallonsTranslator> pip install --upgrade setuptools
Collecting setuptools
  Downloading setuptools-75.8.0-py3-none-any.whl.metadata (6.7 kB)
Downloading setuptools-75.8.0-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 2.0 MB/s eta 0:00:00
Installing collected packages: setuptools
Successfully installed setuptools-75.8.0
(venv) PS C:\code\BallonsTranslator> python .\launch.py
C:\code\BallonsTranslator\launch.py:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
py version:  3.12.8 (tags/v3.12.8:2dc476b, Dec  3 2024, 19:30:04) [MSC v.1942 64 bit (AMD64)]
py executable:  C:\code\BallonsTranslator\venv\Scripts\python.exe
version: 1.4.0
branch: dev
Commit hash: <none>
Installing pywin32
Collecting pywin32
  Using cached pywin32-308-cp312-cp312-win_amd64.whl.metadata (8.3 kB)
Using cached pywin32-308-cp312-cp312-win_amd64.whl (6.5 MB)
Installing collected packages: pywin32
Successfully installed pywin32-308
Installing torch and torchvision
```
用安装这个包就好了`pip install --upgrade setuptools`
