### ISSUE TITLE
请问出现list index out of range

### ISSUE THREAD

**Issue by longfei796** [dmMaze/BallonsTranslator#668]
![0e3c5a65489bfc120d9a78415a474cd](https://github.com/user-attachments/assets/d2f5a280-0e0f-48b4-8082-ddb5d3015dab)
Traceback (most recent call last):
  File "D:\0001翻译文件\[001]\BallonsTranslator_dev_src_with_gitpython\ui\module_manager.py", line 381, in _imgtrans_pipeline
    self.ocr.run_ocr(img, blk_list)
  File "D:\0001翻译文件\[001]\BallonsTranslator_dev_src_with_gitpython\modules\ocr\base.py", line 42, in run_ocr
    self._ocr_blk_list(img, blk_list, *args, **kwargs)
  File "D:\0001翻译文件\[001]\BallonsTranslator_dev_src_with_gitpython\modules\ocr\ocr_mit.py", line 33, in _ocr_blk_list
    return self.model(blk_list, regions, textblk_lst_indices, chunk_size=self.chunk_size)
  File "D:\0001翻译文件\[001]\BallonsTranslator_dev_src_with_gitpython\ballontrans_pylibs_win\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\0001翻译文件\[001]\BallonsTranslator_dev_src_with_gitpython\modules\ocr\mit48px_ctc.py", line 440, in __call__
    textblk = textblk_lst[textblk_lst_indices[i+chunck_idx]]
IndexError: list index out of range

**Comment by dmMaze** [comment]
方便的话原图发我邮箱

**Comment by longfei796** [comment]
> 方便的话原图发我邮箱

请问您什么原图

**Comment by dmMaze** [comment]
> > 方便的话原图发我邮箱
> 
> 请问您什么原图

弹出报错的那张图

**Comment by longfei796** [comment]
> > > 方便的话原图发我邮箱
> > 
> > 
> > 请问您什么原图
> 
> 弹出报错的那张图

抱歉最近有事情忘记了，问题已经解决
