### ISSUE TITLE
在对话内存在Emoji时可以正常识别，但无法进行翻译

### ISSUE THREAD

**Issue by HatsuneDean** [dmMaze/BallonsTranslator#672]
翻译报断言失败：
Traceback (most recent call last):
  File "父路径\BallonsTranslator_dev_src_with_gitpython\ui\module_manager.py", line 467, in run
    self.job()
  File "父路径\BallonsTranslator_dev_src_with_gitpython\ui\module_manager.py", line 307, in <lambda>
    self.job = lambda : self._blktrans_pipeline(blk_list, tgt_img, mode, blk_ids)
  File "父路径\BallonsTranslator_dev_src_with_gitpython\ui\module_manager.py", line 315, in _blktrans_pipeline
    self.translate_thread.module.translate_textblk_lst(blk_list)
  File "父路径\BallonsTranslator_dev_src_with_gitpython\modules\translators\base.py", line 198, in translate_textblk_lst
    _translations = self.translate(text_list)
  File "父路径\BallonsTranslator_dev_src_with_gitpython\modules\translators\base.py", line 159, in translate
    assert len(text_trans) == len(text)
AssertionError
经核实是软件识别了Emoji / ASCII字符 "☆"
可以识别，但是导致翻译时出现错误
（感觉解决起来会比较麻烦，不如直接把emoji屏蔽掉或无脑加在句尾）

**Comment by HatsuneDean** [comment]
另外，画面中的星星(黄色)也被识别成ASCII字符 "★"
同样导致翻译失败

**Comment by dmMaze** [comment]
换一个能处理特殊符号的翻译器，或者在替换原文关键词里把这些符号删掉
