### ISSUE TITLE
module 'torchvision' has no attribute 'ops' 翻译失败

### ISSUE THREAD

**Issue by ok-y** [dmMaze/BallonsTranslator#673]
Traceback (most recent call last):
  File "/Users/BallonsTranslator/ui/module_manager.py", line 366, in _imgtrans_pipeline
    mask, blk_list = self.textdetector.detect(img)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/BallonsTranslator/modules/textdetector/base.py", line 35, in detect
    return self._detect(img)
           ^^^^^^^^^^^^^^^^^
  File "/Users/BallonsTranslator/modules/textdetector/detector_ctd.py", line 61, in _detect
    _, mask, blk_list = self.model(img)
                        ^^^^^^^^^^^^^^^
  File "/Users/.pyenv/versions/3.11.9/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/BallonsTranslator/modules/textdetector/ctd/inference.py", line 331, in __call__
    blks = postprocess_yolo(blks, self.conf_thresh, self.nms_thresh, resize_ratio)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/BallonsTranslator/modules/textdetector/ctd/inference.py", line 238, in postprocess_yolo
    det = non_max_suppression(det, conf_thresh, nms_thresh)[0]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/BallonsTranslator/modules/textdetector/yolov5/yolov5_utils.py", line 202, in non_max_suppression
    i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
        ^^^^^^^^^^^^^^^
AttributeError: module 'torchvision' has no attribute 'ops'

**Comment by dmMaze** [comment]
重新安装 torch 和 torchvision
