### ISSUE TITLE
Translation fails on random pages on dev

### ISSUE THREAD

**Issue by Alexamenus** [dmMaze/BallonsTranslator#686]
[ERROR  ] __init__:create_error_dialog:29 - 52 --> text must be a valid text with maximum 5000 character, otherwise it cannot be translated
Translation Failed.

[ERROR  ] __init__:create_error_dialog:30 - Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\BallonsTranslator_dev_src_with_gitpython\ui\module_manager.py", line 203, in _translate_page
    self.translator.translate_textblk_lst(page)
  File "C:\Users\user\OneDrive\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\base.py", line 205, in translate_textblk_lst
    _translations = self.translate(text_list)
  File "C:\Users\user\OneDrive\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\base.py", line 153, in translate
    text_trans = self._translate(text_source)
  File "C:\Users\user\OneDrive\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_google.py", line 320, in _translate
    translations = [self.googletrans.translate(t) for t in src_list]
  File "C:\Users\user\OneDrive\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_google.py", line 320, in <listcomp>
    translations = [self.googletrans.translate(t) for t in src_list]
  File "C:\Users\user\OneDrive\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_google.py", line 186, in translate
    if self._validate_payload(text):
  File "C:\Users\user\OneDrive\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_google.py", line 60, in _validate_payload
    raise NotValidPayload(payload)
modules.translators.exceptions.NotValidPayload: 52 --> text must be a valid text with maximum 5000 character, otherwise it cannot be translated

**Comment by bropines** [comment]
> [ERROR ] **init**:create_error_dialog:29 - 52 --> text must be a valid text with maximum 5000 character, otherwise it cannot be translated Translation Failed.
> 
> [ERROR ] **init**:create_error_dialog:30 - Traceback (most recent call last): File "C:\Users\user\OneDrive\Desktop\BallonsTranslator_dev_src_with_gitpython\ui\module_manager.py", line 203, in _translate_page self.translator.translate_textblk_lst(page) File "C:\Users\user\OneDrive\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\base.py", line 205, in translate_textblk_lst _translations = self.translate(text_list) File "C:\Users\user\OneDrive\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\base.py", line 153, in translate text_trans = self._translate(text_source) File "C:\Users\user\OneDrive\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_google.py", line 320, in _translate translations = [self.googletrans.translate(t) for t in src_list] File "C:\Users\user\OneDrive\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_google.py", line 320, in translations = [self.googletrans.translate(t) for t in src_list] File "C:\Users\user\OneDrive\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_google.py", line 186, in translate if self._validate_payload(text): File "C:\Users\user\OneDrive\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_google.py", line 60, in _validate_payload raise NotValidPayload(payload) modules.translators.exceptions.NotValidPayload: 52 --> text must be a valid text with maximum 5000 character, otherwise it cannot be translated

It literally tells you that there is an error in the translator. Is the error still ongoing? I can see what's wrong

**Comment by Alexamenus** [comment]
> > [ERROR ] **init**:create_error_dialog:29 - 52 --> text must be a valid text with maximum 5000 character, otherwise it cannot be translated Translation Failed.
> > [ERROR ] **init**:create_error_dialog:30 - Traceback (most recent call last): File "C:\Users\user\OneDrive\Desktop\BallonsTranslator_dev_src_with_gitpython\ui\module_manager.py", line 203, in _translate_page self.translator.translate_textblk_lst(page) File "C:\Users\user\OneDrive\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\base.py", line 205, in translate_textblk_lst _translations = self.translate(text_list) File "C:\Users\user\OneDrive\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\base.py", line 153, in translate text_trans = self._translate(text_source) File "C:\Users\user\OneDrive\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_google.py", line 320, in _translate translations = [self.googletrans.translate(t) for t in src_list] File "C:\Users\user\OneDrive\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_google.py", line 320, in translations = [self.googletrans.translate(t) for t in src_list] File "C:\Users\user\OneDrive\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_google.py", line 186, in translate if self._validate_payload(text): File "C:\Users\user\OneDrive\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_google.py", line 60, in _validate_payload raise NotValidPayload(payload) modules.translators.exceptions.NotValidPayload: 52 --> text must be a valid text with maximum 5000 character, otherwise it cannot be translated
> 
> It literally tells you that there is an error in the translator. Is the error still ongoing? I can see what's wrong

the error message is not correct, it happens on at least 10 pages per 30 pages translated. on varying amounts of text, it can be between one speech bubble, or (most likely the case) the entire page, all of which being between the threshold of 1 - 5000 characters. This leads me to believe that the actual error is in the text detection not the translator but that is just a guess.
I can also affirm that on pages where the program failed in automatic mode with this error, the program has no problem detecting and translating manually within the UI, so it is most certainly a bug.

**Comment by bropines** [comment]
Rather, Google even updated it, so everything broke. I'll fix it later.

**Comment by bropines** [comment]
In the new versions, the developer of Translators seems to have fixed this. I'll close the issue for now

**Comment by Alexamenus** [comment]
I see the discussion got closed, was this fixed? @bropines
