### ISSUE TITLE
判断联网方式有问题，导致无法打开程序EOF occurred in violation of protocol (_ssl.c:1007)

### ISSUE THREAD

**Issue by gsxgmpkt9020** [dmMaze/BallonsTranslator#696]
如何复现：

1. 正常启动
2. 关闭窗口
3. 关闭控制台
4. 再次启动
5. 控制台出现Traceback error

```
D:\Applications\BallonTranslator>cd D:\Applications\BallonTranslator\
py version:  3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
py executable:  D:\Applications\BallonTranslator\ballontrans_pylibs_win\python.exe
version: 1.4.0
branch: dev
Commit hash: <none>
[INFO   ] launch:main:187 - QT_API: pyqt6, QT Version: 6.6.1
Traceback (most recent call last):
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\util\ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "ssl.py", line 513, in wrap_socket
  File "ssl.py", line 1071, in _create
  File "ssl.py", line 1342, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\util\retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='geolocation.onetrust.com', port=443): Max retries exceeded with url: /cookieconsentpub/v1/geo/location (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\translators\server.py", line 333, in get_region_of_server
    data = json.loads(requests.get(self.get_addr_url, headers=_headers_fn(self.get_addr_url)).text[9:-2])
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\requests\adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='geolocation.onetrust.com', port=443): Max retries exceeded with url: /cookieconsentpub/v1/geo/location (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\util\ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "ssl.py", line 513, in wrap_socket
  File "ssl.py", line 1071, in _create
  File "ssl.py", line 1342, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\util\retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ip.taobao.com', port=443): Max retries exceeded with url: /outGetIpInfo (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\translators\server.py", line 340, in get_region_of_server
    data = requests.post(url=self.ip_tb_add_url, data=payload, headers=_headers_fn(self.ip_tb_add_url)).json().get('data')
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\requests\adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='ip.taobao.com', port=443): Max retries exceeded with url: /outGetIpInfo (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Applications\BallonTranslator\launch.py", line 312, in <module>
    main()
  File "D:\Applications\BallonTranslator\launch.py", line 203, in main
    load_modules()
  File "D:\Applications\BallonTranslator\launch.py", line 128, in load_modules
    _load_module(**kwargs)
  File "D:\Applications\BallonTranslator\launch.py", line 120, in _load_module
    importlib.import_module(module_path + module_name.replace('.py', ''))
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Applications\BallonTranslator\modules\translators\trans_trnslatorsmodule.py", line 2, in <module>
    import translators as ts
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\translators\__init__.py", line 5, in <module>
    from translators.server import (
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\translators\server.py", line 5682, in <module>
    tss = TranslatorsServer()
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\translators\server.py", line 5410, in __init__
    self.server_region = self.get_region_of_server(if_print_region=False)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\translators\server.py", line 344, in get_region_of_server
    raise TranslatorError('Unable to connect the Internet.\n\n')
translators.server.TranslatorError: Unable to connect the Internet.
```

如果我继续关掉控制台，那么下次必然正常启动。

顺便看下这启动脚本是否过时了？

```
@REM dependencies\libraries\py310\python.exe F:\repos\BallonsTranslator\ballontranslator
@REM @echo %PATH%

cd %~dp0

@echo off

:: Set the path for PaddleOCR and PyTorch libraries
set "PADDLE_PATH=%~dp0ballontrans_pylibs_win\Lib\site-packages\torch\lib"
set "PATH=%PADDLE_PATH%;%PATH%"

@REM if not defined PYTHON (set PATH=pylibs;pylibs\Scripts;%%PATH%%
set PATH=ballontrans_pylibs_win;ballontrans_pylibs_win\Scripts;PortableGit\cmd;%PATH%
set PYTHON=python.exe

set ERROR_REPORTING=FALSE

mkdir tmp 2>NUL

%PYTHON% -c "" >tmp/stdout.txt 2>tmp/stderr.txt
if %ERRORLEVEL% == 0 goto :check_pip
echo Couldn't launch python
goto :show_stdout_stderr

:check_pip
%PYTHON% -mpip --help >tmp/stdout.txt 2>tmp/stderr.txt
if %ERRORLEVEL% == 0 goto :launch
if "%PIP_INSTALLER_LOCATION%" == "" goto :show_stdout_stderr
%PYTHON% "%PIP_INSTALLER_LOCATION%" >tmp/stdout.txt 2>tmp/stderr.txt
if %ERRORLEVEL% == 0 goto :launch
echo Couldn't install pip
goto :show_stdout_stderr


:launch
%PYTHON% launch.py  %*
pause
exit /b


:show_stdout_stderr

echo.
echo exit code: %errorlevel%

for /f %%i in ("tmp\stdout.txt") do set size=%%~zi
if %size% equ 0 goto :show_stderr
echo.
echo stdout:
type tmp\stdout.txt

:show_stderr
for /f %%i in ("tmp\stderr.txt") do set size=%%~zi
if %size% equ 0 goto :show_stderr
echo.
echo stderr:
type tmp\stderr.txt

:endofscript

echo.
echo Launch unsuccessful. Exiting.
pause
```

**Comment by gsxgmpkt9020** [comment]
不能稳定复现，再观察

**Comment by gsxgmpkt9020** [comment]
太逆天了，难道用连接taobao来判断是否连接到互联网的吗 ？如果我这边解析不了taobao就无法启动了？

```
requests.exceptions.SSLError: HTTPSConnectionPool(host='ip.taobao.com', port=443): Max retries exceeded with url: /outGetIpInfo (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:
```

**Comment by gsxgmpkt9020** [comment]
今天发现换成了httpbin.org，可以打开这个网站（提示这个网站不安全），但是控制台依然报错

**Comment by gsxgmpkt9020** [comment]
```
Commit hash: <none>
[INFO   ] launch:main:213 - QT_API: pyqt6, QT Version: 6.6.1
[INFO   ] import_utils:<module>:53 - PyTorch version 2.0.1+cu118 available.
[INFO   ] import_utils:<module>:53 - PyTorch version 2.0.1+cu118 available.
PyTorch version 2.0.1+cu118 available.
Traceback (most recent call last):
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connectionpool.py", line 1224, in _make_request
    self._validate_conn(conn)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connectionpool.py", line 2274, in _validate_conn
    super()._validate_conn(conn)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connectionpool.py", line 779, in _validate_conn
    conn.connect()
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connection.py", line 810, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connection.py", line 986, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\util\ssl_.py", line 685, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\util\ssl_.py", line 729, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "ssl.py", line 513, in wrap_socket
  File "ssl.py", line 1071, in _create
  File "ssl.py", line 1342, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connectionpool.py", line 1704, in urlopen
    response = self._make_request(  # type: ignore[call-overload,misc]
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connectionpool.py", line 1248, in _make_request
    raise new_e
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connectionpool.py", line 1782, in urlopen
    retries = retries.increment(
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\util\retry.py", line 544, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='geolocation.onetrust.com', port=443): Max retries exceeded with url: /cookieconsentpub/v1/geo/location (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\translators\server.py", line 350, in get_region_of_server
    data = json.loads(requests.get(self.get_addr_url, headers=_headers_fn(self.get_addr_url)).text[9:-2])
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\requests\adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='geolocation.onetrust.com', port=443): Max retries exceeded with url: /cookieconsentpub/v1/geo/location (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connectionpool.py", line 1224, in _make_request
    self._validate_conn(conn)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connectionpool.py", line 2274, in _validate_conn
    super()._validate_conn(conn)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connectionpool.py", line 779, in _validate_conn
    conn.connect()
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connection.py", line 810, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connection.py", line 986, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\util\ssl_.py", line 685, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\util\ssl_.py", line 729, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "ssl.py", line 513, in wrap_socket
  File "ssl.py", line 1071, in _create
  File "ssl.py", line 1342, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connectionpool.py", line 1704, in urlopen
    response = self._make_request(  # type: ignore[call-overload,misc]
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connectionpool.py", line 1248, in _make_request
    raise new_e
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\connectionpool.py", line 1782, in urlopen
    retries = retries.increment(
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\urllib3\util\retry.py", line 544, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ip.taobao.com', port=443): Max retries exceeded with url: /outGetIpInfo (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)')))



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\translators\server.py", line 357, in get_region_of_server
    data = requests.post(url=self.ip_tb_add_url, data=payload, headers=_headers_fn(self.ip_tb_add_url)).json().get('data')
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\requests\adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='ip.taobao.com', port=443): Max retries exceeded with url: /outGetIpInfo (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Applications\BallonTranslator\launch.py", line 344, in <module>
    main()
  File "D:\Applications\BallonTranslator\launch.py", line 229, in main
    load_modules()
  File "D:\Applications\BallonTranslator\launch.py", line 129, in load_modules
    _load_module(**kwargs)
  File "D:\Applications\BallonTranslator\launch.py", line 121, in _load_module
    importlib.import_module(module_path + module_name.replace('.py', ''))
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Applications\BallonTranslator\modules\translators\trans_trnslatorsmodule.py", line 2, in <module>
    import translators as ts
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\translators\__init__.py", line 5, in <module>
    from translators.server import (
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\translators\server.py", line 5906, in <module>
    tss = TranslatorsServer()
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\translators\server.py", line 5632, in __init__
    self.server_region = self.get_region_of_server(if_print_region=False)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\translators\server.py", line 361, in get_region_of_server
    raise TranslatorError('Unable to connect the Internet.\n\n')
translators.server.TranslatorError: Unable to connect the Internet.
```

重新打开又换成taobao来判断联网了，直接导致无法打开程序

**Comment by gsxgmpkt9020** [comment]
```
PS C:\Users\Administrator>  Test-NetConnection ip.taobao.com -port 443


ComputerName     : ip.taobao.com
RemoteAddress    : 198.18.0.15
RemotePort       : 443
InterfaceAlias   : Mihomo
SourceAddress    : 198.18.0.1
TcpTestSucceeded : True
```

**Comment by dmMaze** [comment]
是 ```modules\translators\trans_trnslatorsmodule.py``` 导入的 ```translators``` 会试着联网然后寄。我不想管这种第三方包，现在启动的时候会捕捉异常，之后还是把这种模块改成热加载吧

**Comment by bropines** [comment]
> 是 `modules\translators\trans_trnslatorsmodule.py` 导入的 `translators` 会试着联网然后寄。我不想管这种第三方包，现在启动的时候会捕捉异常，之后还是把这种模块改成热加载吧

this problem is annoying, I will add try catch to the module, I asked the developer to remove the region from forced initialization. Apparently, it won't fix it yet, we'll do it this way.

**Comment by bropines** [comment]
https://github.com/UlionTse/translators/issues/167#issuecomment-2683312745

**Comment by bropines** [comment]
fc157baddd4dc217022b465973f18fe2b5e04201 

Fixed. Sorry :(
