### ISSUE TITLE
IndexError when translate image using manga_ocr as OCR

### ISSUE THREAD

**Issue by mrleteu** [dmMaze/BallonsTranslator#702]
Error happen when i tried to translate certain images using manga_ocr as ocr. (other ocr works fine)

1. If i tried to run Text detection + OCR + Inpaint without Translate, the error did not appear. Then If i run translate, the error happens.

2. When i go to that image and translate manually. it seems that manga_ocr detect the font_size on certain text_block too big. most of the font_size in that image is around 20-35 but, there is one text block font_size with 79. and if i translate that text block, the text_block expand way more than the original and the image. it happens maybe because the japanese word only 4 characters, but the english translate is 13 characters. 

3. In note, if i run translate without update style. The image result is weird. All the text squeeze together into 1 in top right of text block. It can be fixed if i apply font formatting. Normal way like change the font_size do not work.
 
4. But, after this incident. I recall this incident happen a lot before (the text_block expand more than the original, but did not expand more than the image or almost), but the error did not happen. And, if this happen the error text block it will make all the text block in the image behave the same way. It seem only happen when, text inside the "the ballon" on original image leave too much space

Traceback (most recent call last):
  File "D:\Games\Ballon Translator\ui\mainwindow.py", line 481, in pageListCurrentItemChanged
    self.st_manager.updateSceneTextitems()
  File "D:\Games\Ballon Translator\ui\scenetext_manager.py", line 449, in updateSceneTextitems
    blk_item = self.addTextBlock(textblock)
  File "D:\Games\Ballon Translator\ui\scenetext_manager.py", line 465, in addTextBlock
    rst = self.layout_textblk(blk_item, text=translation)
  File "D:\Games\Ballon Translator\ui\scenetext_manager.py", line 842, in layout_textblk
    new_text, xywh, start_from_top, adjust_xy = layout_text(
  File "D:\Games\Ballon Translator\utils\text_layout.py", line 457, in layout_text
    lines, adjust_xy = layout_lines_aligncenter(blk, mask, words, centroid, wl_list, delimiter_len, line_height, spacing, delimiter,
  File "D:\Games\Ballon Translator\utils\text_layout.py", line 198, in layout_lines_aligncenter
    top_mean = mask[pos_y, :].mean()
IndexError: index 109 is out of bounds for axis 0 with size 57

Example: 1. Type of ballon that might be a problem, 2. Another image that got the problem 3. Text Squeeze into
![image](https://github.com/user-attachments/assets/741abe1e-52d4-4985-98e9-dbe5672f680f)
![Screenshot 2024-12-30 180911](https://github.com/user-attachments/assets/9e8088d9-32b6-4ec9-aa19-9455d89d09ff)
![Screenshot 2024-12-30 180659](https://github.com/user-attachments/assets/b5965f54-8647-4914-8377-ff31c51f1858)

**Comment by SkywalkerJi** [comment]
same error

**Comment by dmMaze** [comment]
It should be fixed by [c5f36fc](https://github.com/dmMaze/BallonsTranslator/commit/c5f36fcc5fdb6a7e3237af587f3712c0a0adc42f)

**Comment by mrleteu** [comment]
oke thanks, it works fine now.
