### ISSUE TITLE
How to change max_tokens to max_completion_tokens?

### ISSUE THREAD

**Issue by weskeryiu** [dmMaze/BallonsTranslator#704]
I try to use OpenAI o1-preview in BallonsTranslator but I get "‘max_tokens’ is not supported with this model. Use ‘max_completion_tokens’ instead."

**Comment by dmMaze** [comment]
Please update to [23b962a](https://github.com/dmMaze/BallonsTranslator/commit/23b962ab618c8717a32a1162540512ced4875d91)

**Comment by weskeryiu** [comment]
> Please update to [23b962a](https://github.com/dmMaze/BallonsTranslator/commit/23b962ab618c8717a32a1162540512ced4875d91)

Hello, I updated the BallonsTranslator, but this time I got the following error:

[WARNING] trans_chatgpt:_translate:264 - Translation failed due to Completions.create() got an unexpected keyword argument 'presence_penalty '. Attempt: 3, sleep for 15 secs...
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\weske\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_chatgpt.py", line 239, in _translate
    response = self._request_translation(prompt, chat_sample)
  File "C:\Users\weske\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_chatgpt.py", line 397, in _request_translation
    return self._request_translation_with_chat_sample(prompt, model, chat_sample)
  File "C:\Users\weske\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_chatgpt.py", line 336, in _request_translation_with_chat_sample
    response = openai_chatcompletions_create(**func_args)
  File "C:\Users\weske\Desktop\BallonsTranslator_dev_src_with_gitpython\ballontrans_pylibs_win\lib\site-packages\openai\_utils\_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
TypeError: Completions.create() got an unexpected keyword argument 'presence_penalty '

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1100, in emit
  File "logging\__init__.py", line 943, in format
  File "C:\Users\weske\Desktop\BallonsTranslator_dev_src_with_gitpython\utils\logger.py", line 40, in format
    record.message2 = colored(record.getMessage())
  File "logging\__init__.py", line 368, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\Users\weske\Desktop\BallonsTranslator_dev_src_with_gitpython\ui\module_manager.py", line 81, in run
    self.job()
  File "C:\Users\weske\Desktop\BallonsTranslator_dev_src_with_gitpython\ui\module_manager.py", line 232, in _run_translate_pipeline
    self._translate_page(self.imgtrans_proj.pages, page_key, emit_finished=False)
  File "C:\Users\weske\Desktop\BallonsTranslator_dev_src_with_gitpython\ui\module_manager.py", line 203, in _translate_page
    self.translator.translate_textblk_lst(page)
  File "C:\Users\weske\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\base.py", line 205, in translate_textblk_lst
    _translations = self.translate(text_list)
  File "C:\Users\weske\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\base.py", line 149, in translate
    text_trans = self._translate(text_source)
  File "C:\Users\weske\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_chatgpt.py", line 265, in _translate
    self.logger.error(f'Request traceback: ', traceback.format_exc())
  File "logging\__init__.py", line 1506, in error
  File "logging\__init__.py", line 1624, in _log
  File "logging\__init__.py", line 1634, in handle
  File "logging\__init__.py", line 1696, in callHandlers
  File "logging\__init__.py", line 968, in handle
  File "logging\__init__.py", line 1108, in emit
Message: 'Request traceback: '
Arguments: ('Traceback (most recent call last):\n  File "C:\\Users\\weske\\Desktop\\BallonsTranslator_dev_src_with_gitpython\\modules\\translators\\trans_chatgpt.py", line 239, in _translate\n    response = self._request_translation(prompt, chat_sample)\n  File "C:\\Users\\weske\\Desktop\\BallonsTranslator_dev_src_with_gitpython\\modules\\translators\\trans_chatgpt.py", line 397, in _request_translation\n    return self._request_translation_with_chat_sample(prompt, model, chat_sample)\n  File "C:\\Users\\weske\\Desktop\\BallonsTranslator_dev_src_with_gitpython\\modules\\translators\\trans_chatgpt.py", line 336, in _request_translation_with_chat_sample\n    response = openai_chatcompletions_create(**func_args)\n  File "C:\\Users\\weske\\Desktop\\BallonsTranslator_dev_src_with_gitpython\\ballontrans_pylibs_win\\lib\\site-packages\\openai\\_utils\\_utils.py", line 275, in wrapper\n    return func(*args, **kwargs)\nTypeError: Completions.create() got an unexpected keyword argument \'presence_penalty \'\n',)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\weske\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_chatgpt.py", line 239, in _translate
    response = self._request_translation(prompt, chat_sample)
  File "C:\Users\weske\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_chatgpt.py", line 397, in _request_translation
    return self._request_translation_with_chat_sample(prompt, model, chat_sample)
  File "C:\Users\weske\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_chatgpt.py", line 336, in _request_translation_with_chat_sample
    response = openai_chatcompletions_create(**func_args)
  File "C:\Users\weske\Desktop\BallonsTranslator_dev_src_with_gitpython\ballontrans_pylibs_win\lib\site-packages\openai\_utils\_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
TypeError: Completions.create() got an unexpected keyword argument 'presence_penalty '

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1100, in emit
  File "logging\__init__.py", line 943, in format
  File "logging\__init__.py", line 678, in format
  File "logging\__init__.py", line 368, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\Users\weske\Desktop\BallonsTranslator_dev_src_with_gitpython\ui\module_manager.py", line 81, in run
    self.job()
  File "C:\Users\weske\Desktop\BallonsTranslator_dev_src_with_gitpython\ui\module_manager.py", line 232, in _run_translate_pipeline
    self._translate_page(self.imgtrans_proj.pages, page_key, emit_finished=False)
  File "C:\Users\weske\Desktop\BallonsTranslator_dev_src_with_gitpython\ui\module_manager.py", line 203, in _translate_page
    self.translator.translate_textblk_lst(page)
  File "C:\Users\weske\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\base.py", line 205, in translate_textblk_lst
    _translations = self.translate(text_list)
  File "C:\Users\weske\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\base.py", line 149, in translate
    text_trans = self._translate(text_source)
  File "C:\Users\weske\Desktop\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_chatgpt.py", line 265, in _translate
    self.logger.error(f'Request traceback: ', traceback.format_exc())
  File "logging\__init__.py", line 1506, in error
  File "logging\__init__.py", line 1624, in _log
  File "logging\__init__.py", line 1634, in handle
  File "logging\__init__.py", line 1696, in callHandlers
  File "logging\__init__.py", line 968, in handle
  File "logging\__init__.py", line 1218, in emit
  File "logging\__init__.py", line 1108, in emit
Message: 'Request traceback: '
Arguments: ('Traceback (most recent call last):\n  File "C:\\Users\\weske\\Desktop\\BallonsTranslator_dev_src_with_gitpython\\modules\\translators\\trans_chatgpt.py", line 239, in _translate\n    response = self._request_translation(prompt, chat_sample)\n  File "C:\\Users\\weske\\Desktop\\BallonsTranslator_dev_src_with_gitpython\\modules\\translators\\trans_chatgpt.py", line 397, in _request_translation\n    return self._request_translation_with_chat_sample(prompt, model, chat_sample)\n  File "C:\\Users\\weske\\Desktop\\BallonsTranslator_dev_src_with_gitpython\\modules\\translators\\trans_chatgpt.py", line 336, in _request_translation_with_chat_sample\n    response = openai_chatcompletions_create(**func_args)\n  File "C:\\Users\\weske\\Desktop\\BallonsTranslator_dev_src_with_gitpython\\ballontrans_pylibs_win\\lib\\site-packages\\openai\\_utils\\_utils.py", line 275, in wrapper\n    return func(*args, **kwargs)\nTypeError: Completions.create() got an unexpected keyword argument \'presence_penalty \'\n',)

**Comment by dmMaze** [comment]
> Hello, I updated the BallonsTranslator, but this time I got the following error:

[a97a774](https://github.com/dmMaze/BallonsTranslator/commit/a97a77468741d1e92e3e919b19326ff71f106a61) should fix it

**Comment by weskeryiu** [comment]
> > Hello, I updated the BallonsTranslator, but this time I got the following error:
> 
> [a97a774](https://github.com/dmMaze/BallonsTranslator/commit/a97a77468741d1e92e3e919b19326ff71f106a61) should fix it

Thanks. It's working now, but some changes needed to be made manually. The o1-preview model doesn't support the 'system' role and doesn't support temperature 0.5. After I changed 'role' from 'system' to 'user' in line 308 of trans_chatgpt.py and set the temperature to 1 in the BalloonTranslator settings, it worked.
