### ISSUE TITLE
Suddenly MANGA_OCR & OPENCV ERRORS!

### ISSUE THREAD

**Issue by gsxgmpkt9020** [dmMaze/BallonsTranslator#705]
MANGA_OCR:

```

Traceback (most recent call last):
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\transformers\feature_extraction_utils.py", line 430, in get_feature_extractor_dict
    resolved_feature_extractor_file = cached_file(
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\transformers\utils\hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\huggingface_hub\utils\_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\huggingface_hub\utils\_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'data/models/manga-ocr-base'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Applications\BallonTranslator\ui\module_manager.py", line 381, in _imgtrans_pipeline
    self.ocr.run_ocr(img, blk_list)
  File "D:\Applications\BallonTranslator\modules\ocr\base.py", line 30, in run_ocr
    self.load_model()
  File "D:\Applications\BallonTranslator\modules\base.py", line 138, in load_model
    self._load_model()
  File "D:\Applications\BallonTranslator\modules\ocr\ocr_manga.py", line 66, in _load_model
    self.model = MangaOcr(device=self.device)
  File "D:\Applications\BallonTranslator\modules\ocr\ocr_manga.py", line 14, in __init__
    self.feature_extractor = AutoFeatureExtractor.from_pretrained(pretrained_model_name_or_path)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\transformers\models\auto\feature_extraction_auto.py", line 312, in from_pretrained
    config_dict, _ = FeatureExtractionMixin.get_feature_extractor_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\Applications\BallonTranslator\ballontrans_pylibs_win\lib\site-packages\transformers\feature_extraction_utils.py", line 448, in get_feature_extractor_dict
    raise EnvironmentError(
OSError: Can't load feature extractor for 'data/models/manga-ocr-base'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'data/models/manga-ocr-base' is the correct path to a directory containing a preprocessor_config.json file

```

OPENCV

```
Traceback (most recent call last):
  File "D:\Applications\BallonTranslator\ui\module_manager.py", line 365, in _imgtrans_pipeline
    mask, blk_list = self.textdetector.detect(img)
  File "D:\Applications\BallonTranslator\modules\textdetector\base.py", line 37, in detect
    self.load_model()
  File "D:\Applications\BallonTranslator\modules\base.py", line 138, in load_model
    self._load_model()
  File "D:\Applications\BallonTranslator\modules\textdetector\detector_ctd.py", line 58, in _load_model
    self.model = load_ctd_model(CTD_ONNX_PATH, self.device, self.detect_size)
  File "D:\Applications\BallonTranslator\modules\textdetector\detector_ctd.py", line 11, in load_ctd_model
    model = CTDModel(model_path, detect_size=detect_size, device=device)
  File "D:\Applications\BallonTranslator\modules\textdetector\ctd\inference.py", line 270, in __init__
    self.load_model(model_path)
  File "D:\Applications\BallonTranslator\modules\textdetector\ctd\inference.py", line 276, in load_model
    self.net = TextDetBaseDNN(1024, model_path)
  File "D:\Applications\BallonTranslator\modules\textdetector\ctd\basemodel.py", line 242, in __init__
    self.model = cv2.dnn.readNetFromONNX(model_path)
cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:277: error: (-5:Bad argument) Can't read ONNX file: data/models/comictextdetector.pt.onnx in function 'cv::dnn::dnn4_v20240521::ONNXImporter::ONNXImporter'
```

**Comment by gsxgmpkt9020** [comment]
```
qt.svg: Cannot open file 'D:/Komga/icons/leftbar_config_activate.svg', because: The system cannot find the path specified.
qt.svg: Cannot open file 'D:/Komga/icons/leftbar_config_activate.svg', because: The system cannot find the path specified.
qt.svg: Cannot open file 'D:/Komga/icons/leftbar_imgtrans_activate.svg', because: The system cannot find the path specified.
qt.svg: Cannot open file 'D:/Komga/icons/leftbar_imgtrans_activate.svg', because: The system cannot find the path specified.
qt.svg: Cannot open file 'D:/Komga/icons/search_activate.svg', because: The system cannot find the path specified.
qt.svg: Cannot open file 'D:/Komga/icons/search_activate.svg', because: The system cannot find the path specified.
qt.svg: Cannot open file 'D:/Komga/icons/showpagelist_activate.svg', because: The system cannot find the path specified.qt.svg: Cannot open file 'D:/Komga/icons/showpagelist_activate.svg', because: The system cannot find the path specified.[INFO   ] config:save_config:216 - Config saved
[ERROR  ] __init__:create_error_dialog:29 - OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:277: error: (-5:Bad argument) Can't read ONNX file: data/models/comictextdetector.pt.onnx in function 'cv::dnn::dnn4_v20240521::ONNXImporter::ONNXImporter'
```

**Comment by gsxgmpkt9020** [comment]
可能是关机的时候文件损坏了,覆盖安装DEV版后好了
