### ISSUE TITLE
GOOGLE翻譯出現錯誤

### ISSUE THREAD

**Issue by TMHINKH** [dmMaze/BallonsTranslator#83]
選擇GOOGLE翻譯時出現以下錯誤
使用GOOGLE翻譯還需要額外設定嗎?
位置在中國大陸以外應該不需設代理了吧
[ERROR  ] dl_manager:handleRunTimeException:806 - Translation Failed.: RequestError()
Traceback (most recent call last):
  File "C:\BALLON~1\BALLON~1\ui\dl_manager.py", line 190, in _translate_page
  File "C:\BALLON~1\BALLON~1\dl\translators\__init__.py", line 169, in translate_textblk_lst
  File "C:\BALLON~1\BALLON~1\dl\translators\__init__.py", line 136, in translate
  File "C:\BALLON~1\BALLON~1\dl\translators\__init__.py", line 231, in _translate
  File "C:\BALLON~1\BALLON~1\dl\translators\google_trans.py", line 193, in translate
dl.translators.exceptions.RequestError: Request exception can happen due to an api connection error. Please check your connection and try again

**Comment by dmMaze** [comment]
设置里谷歌翻译url后缀如果是.cn就改成.com

**Comment by TMHINKH** [comment]
> 设置里谷歌翻译url后缀如果是.cn就改成.com

剛試了一下用，1.3.0版沒問題
但把1.3.27覆蓋進去後，就會有問題
1.3.27覆蓋進去後GOOGLE翻譯只剩下.COM可以選，.CN已經沒了

**Comment by dmMaze** [comment]
> > 设置里谷歌翻译url后缀如果是.cn就改成.com
> 
> 剛試了一下用，1.3.0版沒問題 但把1.3.27覆蓋進去後，就會有問題 1.3.27覆蓋進去後GOOGLE翻譯只剩下.COM可以選，.CN已經沒了

代码里忘了改一个地方，请更新到1.3.28
